### ISSUE TITLE
Login user experience: openbox default settings move

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#1057]
My panel was like this:
![screen-2016-05-22-16-04-51](https://cloud.githubusercontent.com/assets/62877/15480589/47c2829c-211e-11e6-950a-d75ab860bb92.png)

After I updated and installed lxqt-common in the next login I got this:
![screen-2016-05-22-16-12-27](https://cloud.githubusercontent.com/assets/62877/15480599/506587b4-211e-11e6-9a1d-0740456834ec.png)

I just typed my password and left. And when I come back stared at the screen and thinking: What's just happened. The panel covered the xmessage. And the numbers of desktops had changed.
Just figured it out because remembered the openbox settings moving discussion.

It was not a good experience to me. I doubt that it will be for a "regular" user.

**Comment by tsujan** [comment]
I wanted to write this on the page about moving openbox settings:

Backward compatibility is among the most important things devs should respect. Please never break it, unless there's really no other choice! At least, don't break it based on mere speculations!

**Comment by palinek** [comment]
Guys, please, consider if the lxde/lxqt-common#53 can be considered as fix for this...

**Comment by pmattern** [comment]
Meanwhile we [started wondering](https://github.com/lxde/lxqt-common/pull/54#issuecomment-229343422) whether it would make sense to consider preexisting configurations due to using Openbox under LXDE as well, hence `~/.config/openbox/lxde-rc.xml`.
@palinek Thoughts? Should we extend the logic introduced in lxde/lxqt-common#53 to not only consider `~/.config/openbox/rc.xml` but `~/.config/openbox/lxde-rc.xml` as well?

(Btw. if we should decide not to this issue can get closed.)

**Comment by palinek** [comment]
@pmattern see the lxde/lxqt-common#57

**Comment by paulolieuthier** [comment]
Did lxde/lxqt-common#53 fix it?

**Comment by palinek** [comment]
Both pre-existing OB config files (rc.xml & lxde-rc.xml) are now considered/copied before OB is started and optional message is displayed to the user.

Closing this...
