### ISSUE TITLE
Consider replacing all Q_FOREACH/foreach loops with the c++ range-based loops

### ISSUE THREAD

**Issue by palinek** [lxde/lxqt#1060]
I'm in flavour of replacing all Q_FOREACH by the [c++ range-based loops](http://en.cppreference.com/w/cpp/language/range-for) as the [Q_FOREACH is going to be deprecated](https://codereview.qt-project.org/#/c/147363/).

Opinions? Pros/cons?

**Comment by luis-pereira** [comment]
@palinek 
I'm not so sure that `Q_FOREACH` will be deprecated. The discussion it's still going on. It's use is discouraged,  no doubt about that.
I'm in favor of using the C++ range-base loops. They are clean an concise. But we have a couple of three problems:

1. We need `qAsConst()` to prevent implicitly-shared Qt containers from detaching:
``` C++
    QString s = ...;

    for (QChar ch : s) // detaches 's' (performs a deep-copy if 's' was shared)
        process(ch);

    for (QChar ch : qAsConst(s)) // ok, no detach attempt
        process(ch);
```
2. `qAsConst()` is only available on Qt 5.7
3.   [C++17 std::as_const()](http://en.cppreference.com/w/cpp/utility/as_const) is also not currently available. [GCC 6.1 C++17](http://coliru.stacked-crooked.com/view?id=af26910c1c1949ff) and [Clang 3.8 C++17](http://coliru.stacked-crooked.com/view?id=37cc44a7199fe4c5) can't handle it.

Of course we can workaround point 1, by declaring using:
``` C++
const QString s =......;
for (QChar ch: s) // ok, no detach on an const object
    process(ch);
```

I'm all in favor of start using it, when appropriate. No so much of replacing it entirely, for now.

**Comment by paulolieuthier** [comment]
More info here: http://www.dvratil.cz/2015/06/qt-containers-and-c11-range-based-loops/.

**Comment by r-a-v-a-s** [comment]
`foreach(const QString &option, optionList) { ... }`

`for (const QString &option : optionList) { ... }`

>There is a slight difference between the two: Qt does a copy of the container before iterating.
This is cheap for Qt container as they use implicit sharing, but is expensive with standard containers that do a deep copy of the whole content.
The C++0x range-based for does not copy, which means the behaviour is undefined if you add or remove items from the container as you iterate.
The new for will call the begin() and end() functions which are going to make a copy of the Qt container if it is shared and non const. Hence, it is better to pass const containers.

http://blog.qt.io/blog/2011/05/26/cpp0x-in-qt/

My understanding of implicit sharing is that with foreach 
if we have a "QContainer" which holds "QObjects"
then copying only happens if we try to modify the container (i.e. copy on write).
But I can't say for sure... ;-]

**Comment by palinek** [comment]
Follow up in #1325
