### ISSUE TITLE
after building from source, no options for lxqt to login

### ISSUE THREAD

**Issue by jimmyoic** [lxde/lxqt#1064]
Hi,

My environment is Ubuntu 16.04, try to build lxqt on my virtual machine which is fresh before 

I install build-essential by apt-get

I follow 

https://github.com/lxde/lxqt/wiki/Building-From-Source

to build  lxqt project

After the installation is done, I restart my virtual machine

but there are only two choices "Ubuntu default" and "Openbox" for me, still, without lxqt

Have I missed something?

**Comment by stefonarch** [comment]
What display manager are you using? Sddm is recommended.

**Comment by jimmyoic** [comment]
it's lightdm
I'll try Sddm and then report here 
thanks.

**Comment by f2404** [comment]
This works for me with lightdm:
```
$ cat ~/.xinitrc 
exec startlxqt
```

**Comment by jimmyoic** [comment]
hi
I try sddm and the problem still there,
I suppose that its not the thing of lightdm

**Comment by stefonarch** [comment]
Check in  /usr/share/xsessions/ there should be a file lxqt.desktop 
[Desktop Entry]
Type=Application
Exec=startlxqt
TryExec=lxqt-session
Name=LXQt Desktop
Comment=Lightweight Qt Desktop

**Comment by pmattern** [comment]
When `lxqt-common` gets installed according to the sections about single components in https://github.com/lxde/lxqt/wiki/Building-From-Source desktop entry file `lxqt.desktop` will be placed in `/usr/local/share/xsession` but the display managers expect it in `/usr/share/xsessions`. Copying the file or creating a symbolic link will make the LXQt session appear in the display managers. Same findings with LightDM and SDDM.
Also, you have to make sure both binaries `startlxqt` and `lxqt-session` are available in `PATH` which can be checked by running `$ which startlxqt lxqt-session`. Both are needed to handle the LXQt session, lack of the latter will prevent file `lxqt.desktop` from displaying due to line `TryExec=lxqt-session`.

Not sure whether the said wiki page should be complemented with CMake variable `CMAKE_INSTALL_PREFIX` which would prevent all these problems.

**Comment by jimmyoic** [comment]
Hi,
I solve this problem by changing default qt version by modified
/usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf  from qt4 to qt5
(modified the content to /usr/lib/x86_64-linux-gnu/qt5/bin)

I also tried to export the PATH like what [https://github.com/lxde/lxqt/wiki/Building-From-Source] said
but instead of that this way works. Not quite sure why the different version of qt cause such a problem

thanks to you guys comment !
