### ISSUE TITLE
Setting user dirs in lxqt-session GUI brakes desktop path

### ISSUE THREAD

**Issue by scheunemann** [lxde/lxqt#1074]
I didn't look into the code so far, so I am not sure whether it is an issue with populating user directories in via the `session GUI` or whether it is an issue with XDG issue, so I decided to place it here first.

If `$HOME/.config/user-dirs.dirs` doesn't exist, and a directory is changed via `Preferences->LXQt-Settings->Session Settings` (session GUI), the desktop shows content of the root directory afterwards.

A workaround is to change the Desktop in `Preferences->LXQt-Settings->Session Settings` to something else other then the default (to trigger an entry in user-dirs I assume), or by manually adding `XDG_DESKTOP_DIR="$HOME/Desktop"`
to the file `user-dirs.dirs`.

**Comment by pmattern** [comment]
On your system `~/.config/user-dirs.dirs` is missing besides an LXQt session was started before. This plus your findings are strongly suggesting you are lacking binaries `xdg-user-dir[s-update]`. Lack of these binaries is probably not unlikely for now as support of xdg-user-dirs was introduced not that long ago so maybe not all downstream LXQt packages are already depending on the packages providing those binaries.

This problem was already discussed in #896 so I'm closing this one as a duplicate. Feel free to let us know if you think your issue is different. But if so please let us know which distribution you're using and how LXQt was installed.
