### ISSUE TITLE
usr/bin/startlxqt doesn't allow to set environments on libreoffice-still.

### ISSUE THREAD

**Issue by githubtefo** [lxde/lxqt#1113]
Hi!
Given this is my first time writing you, first of all, great thanks to this community. I'm in love with my LXqt Desktop Environment :)

Well, on Arch, since last libreoffice-still version it uses gtk3 as the default environment, despite it is reported as currently broken.
Many of us tried to replace gtk3 for gen environment uncommenting the `SAL_USE_VCLPLUGIN gen` option on `/etc/profile.d/libreoffice-still.{sh|csh}`
But the variable is overwriting to `kde4` on lxqt by `usr/bin/startlxqt`.

An Arch linux forum discussion about this issue resulted on this suggestion:
Use this: `export SAL_USE_VCLPLUGIN="${SAL_USE_VCLPLUGIN:-kde4}"`
instead of:
```
# Enable Qt integration for OpenOffice.org, if available.
export SAL_USE_VCLPLUGIN=kde4
```
[bbs.archlinux.org/viewtopic.php?pid=1647080#p1647080](https://bbs.archlinux.org/viewtopic.php?pid=1647080#p1647080)

**Comment by pmattern** [comment]
In dialogue "LXQt Session Setings" (binary `lxqt-config-session`) - Environment (Advanced) custom environment variables can be added and preexisting ones can be modified. Both is valid for the LXQt session as a whole.
Modifying `SAL_USE_VCLPLUGIN` that way has its expected effect as can be verified in shell sessions running in a terminal emulator in an LXQt session
```
$ env | grep VCL 
SAL_USE_VCLPLUGIN=gen
```
and by launching LibreOffice ("fresh" here, but shouldn't make a difference) and e. g. looking at the file chooser.
Please verify on your system. Don't forget to restart the LXQt session after tweaking the settings in `lxqt-config-session`.

The precedence of environment variable settings is `/etc/profile.d/*.sh` < `startlxqt` < `lxqt-config-session` which is absolutely the right thing to to, IMO.
In `startlxqt` we modify only those every environment variables where a particular value can be assumed to be the right one on LXQt so values set by this script should take precedence over the rather generic settings in `/etc/profile.d`. And of course the values set by `lxqt-config-session` should have the highest priority in order to allow users to define custom settings independent of the two other locations which can be modified by system administrators only.

The only thing weird is why `kde4` doesn't seem to be the right value any longer. We've been discussing the value a while ago in #544 and it seemed to be the right choice then.
But strictly speaking this is an issue different from the one discussed here.

**Comment by palinek** [comment]
@pmattern You're right with the possibility to change the env. vars via the `lxqt-config-session`, but in startlxqt we do honor the pre-defined user's variables, see e.g. [here](https://github.com/lxde/lxqt-common/blob/master/startlxqt.in#L9) => I think this is a perfectly valid request.

@githubtefo please, confirm, that lxde/lxqt-common@f86144f does the trick for you.

**Comment by pmattern** [comment]
This issue is not about overwriting user-specific but system-wide settings.
These apply to all users and all kinds of desktop sessions as well. The latter is the reason why I still think overwriting is the right thing to do as long as we allow users to apply their own custom settings at the highest precedence which is what we do.
In other words, if a system administrator sets `export SAL_USE_VCLPLUGIN=gtk3` in `/etc/profile.d/libreoffice.sh`, e. g. as the majority of users on a particular system is using GNOME, then LibreOffice will by default use the GTK plugin in LXQt sessions running the current lxde/lxqt-common@f86144f.
Do you really think this is what we want?

**Comment by githubtefo** [comment]
Very interesting discussion.
@palinek, [https://github.com/lxde/lxqt-common/commit/f86144f](url) works very well here: now my system uses the configuration of `/etc/profile.d/libreoffice-still.{sh|csh}`
@pmattern, I opened the issue because the new environment works too badly, specially the scroll pad function. I assume it should be gtk3, because libreoffice reports it uses this since the last version (and also given that the environment is setting as kde4, and we don't have the libs).
Regarding your discussion about who should set certain variables, in my case when I wanted to change the aspect of Libreoffice I recurred to the libreoffice's Arch wiki. When nothing happened, I posted into the Arch forum and finally came here. I just figure out what was the intuitive places for me, a non-advanced non-coder linux user. Take into account that many features of lxqt are still experimental, so it is important that users can find easily how to solve eventual problems.

**Comment by tsujan** [comment]
It was a strange coincidence that after using LibreOffice under LXQt for so much time, a few days ago I edited `/etc/profile.d/libreoffice-still.sh` and thought LibreOffice should have a bug because no change happened. It didn't occur to me that the problem may be in LXQt. Then, yesterday @palinek made the commit https://github.com/lxde/lxqt-common/commit/f86144f and it worked :)

**Comment by palinek** [comment]
> E. g. if a system administrator sets export SAL_USE_VCLPLUGIN=gtk3 in /etc/profile.d/libreoffice.sh as the majority of users on a particular system is using GNOME then LibreOffice will by default use the GTK plugin in LXQt sessions as well running current lxde/lxqt-common@f86144f.
Is this really what we want?

I think we shouldn't force anything. In your scenario, if the administrator want to do it, it's his/her responsibility. The very same way he/she can install only the GTK style for libreoffice and then setting the `SAL_USE_VCLPLUGIN` to `kde*` will also be functionless. Should everything needed be installed, the "poor" user can still change the env. var as you've described it.

**Comment by pmattern** [comment]
This is indeed a point I've missed.
My idea was "Let's do what's best for LXQt independent from what an administrator may set system-wide." But in contrast to GTK where the VCL plugin is interacting with the widget toolkit itself it's only interacting with kdelibs as far as the Qt ecosystem is concerned. But unlike the toolkits this component isn't necessarily installed so we are already depending on the administrator anyway.
So probably your solution is indeed right and we should probably close this again.

**Comment by palinek** [comment]
> So probably your solution is indeed right and we should probably close this again.

If there is nothing to say here, feel free to close it.
