### ISSUE TITLE
libqtxdg: lxqt no longer can start X

### ISSUE THREAD

**Issue by ms6676749** [lxde/lxqt#1142]
Arch linux
libqtxdg-git-1.3.0.63.gfce7ad1-1-x86_64.pkg.tar.xz

After just updating to the latest git comments, lxqt can no longer start under X:
`lxqt-session: error while loading shared libraries: libQt5Xdg.so.1: cannot open shared object file: No file or directory
xinit: connection to X server lost` 

The latest git build of libqtxdg apparently doesn't contain libQt5Xdg.so.1 whereas the `libqtxdg-git-1.3.0.62.gc6cae3c-1-x86_64.pkg.tar.xz` package I built three days ago did.  Downgrading to the older package didn't work as lxqt's X session now requires libQt5Xdg.so.2, which the older package didn't contain.

**Comment by ms6676749** [comment]
Here's a list of the upgraded git packages made earlier that produced this issue:
`[2016-09-16 08:27] [ALPM] upgraded libqtxdg-git (1.3.0.62.gc6cae3c-1 -> 1.3.0.63.gfce7ad1-1)
[2016-09-16 08:32] [ALPM] upgraded liblxqt-git (0.10.0.56.g63b8dfe-1 -> 0.10.0.58.gb1b249e-1)
[2016-09-16 08:33] [ALPM] upgraded lxqt-admin-git (0.10.0.28.g19cc226-1 -> 0.10.0.29.g3309194-1)
[2016-09-16 08:36] [ALPM] upgraded lxqt-config-git (0.10.0.69.g2c24a41-1 -> 0.10.0.73.g98d938b-1)
[2016-09-16 08:39] [ALPM] upgraded lxqt-panel-git (0.10.0.139.g46ecc30-1 -> 0.10.0.142.g5cda400-1)
[2016-09-16 08:39] [ALPM] upgraded lxqt-policykit-git (0.10.0.9.gc393247-1 -> 0.10.0.13.gc005447-1)
[2016-09-16 08:39] [ALPM] upgraded lxqt-qtplugin-git (0.10.0.9.gabfdcb1-1 -> 0.10.0.10.gb98b8d0-1)`

**Comment by pmattern** [comment]
Latest checkouts of all LXQt components are working flawlessly on Arch Linux here, no matter whether the session is launched from a virtual terminal or by SDDM. This plus the messages you've posted strongly suggests there's some problem at your side due to the soname bump that was introduced in libqtxdg lately and necessary with regards to the upcoming LXQt release.

Did you really compile *all* components against the new libqtxdg? Basically this means to re-compile LXQt as a whole as nearly all components are depending on it directly or via dependency liblxqt.
If unsure the order in which they have to be compiled is listed at https://github.com/lxde/lxqt/wiki/Building-from-source#general. Also, you may use a script like this one https://gist.github.com/pmattern/8056c4bd7104ae640b79. With regards to this report I'd refrain from using metapackage lxqt-desktop-git, though, as you can never really know whether AUR helpers are installing in an unsuitable order then.

**Comment by paulolieuthier** [comment]
Reopen if necessary.

**Comment by ms6676749** [comment]
@pmattern 

I don't use the AUR script.  I have my own bash script that checks out lxqt components from git and builds the associated packages if there's been a commit change.  The issue is likely like you said that I have to rebuild the rest of the components against the version bump in lxqtxdg, which is pretty simple.  If there's any issue similar to this after the full rebuild, then I'll reopen this report.

**Comment by agaida** [comment]
then one should rewrite his scripts and build all needed components in the right™ build  order - and make sure that the new components are installed and available if the next components need them as build dependency. And btw - there is no  libQt5Xdg.so.1 and now libqtxdg 1.3 anymore ..  esp. in git

**Comment by pmattern** [comment]
> and builds the associated packages *if there's been a commit change*.

Then you're in for trouble. It's not sufficient to rebuilt a particular component when its own code was changed but when there are changes regarding its dependencies as well.
Probably this is exactly the reason of the trouble you've been reporting.
If you install LXQt from the sources it is always best to install *all* components each time. That way you may install one component or the other without a real need but this is still less work than tracing down problems like the one you've reported here.

**Comment by paulolieuthier** [comment]
> If you install LXQt from the sources it is always best to install all components each time.

That, of course, will only be necessary for major releases soon™, as we will be respecting the laws of libraries versioning.

**Comment by ms6676749** [comment]
@agaida 

Please don't make assumptions: https://bbs.archlinux.org/viewtopic.php?id=213836

Removing the --needed flag will accomplish what @pmattern suggested; it is that easy.  The 1.3 version is just a placeholder and has no effect on what is fetched from git; it could be any number the user wants it to be.  In fact, the PKGBUILD for libqtxdg-git on AUR is 1.2.

**Comment by agaida** [comment]
There was no assumtions - if a .so.1 is missed because it's bumped to .so.2 - there can be three things wrong: build order, no current build dependencies, not all packages built - nothing less, nothing more. But hey - i'm only a part time arch user, mostly to get the newest and freshest Qt and KF 5 Regressions (btw. not Archs fault).

**Comment by stefonarch** [comment]
Running in similar problems, first I updated libqtxdg-git and libsysstat-git from AUR then nothing builds anymore:

CMake Error at /usr/share/cmake/qt5xdg/qt5xdg-targets.cmake:76 (message):
  The imported target "Qt5Xdg" references the file

     "/usr/lib64/libQt5Xdg.so.1.3.0"

**Comment by pmattern** [comment]
@stefonarch 
Recently there was a soname bump in libqtxdg, see e. g. http://lxqt.org/release/2016/09/17/libsysstat-032-libqtxdg-200/. This means that all LXQt components have to be re-built once a libqtxdg commit featuring the new soname is used.
This is probably the underlying problem of what you've written here as well as in #1145.
