### ISSUE TITLE
Why do some windows lack minimize buttions in LXQT?

### ISSUE THREAD

**Issue by vonHabsi** [lxde/lxqt#1179]
![selection_023](https://cloud.githubusercontent.com/assets/200945/19518489/61b59c60-95ff-11e6-8fca-d0daa7dd869b.png)
![selection_024](https://cloud.githubusercontent.com/assets/200945/19518492/61d7d99c-95ff-11e6-99fb-1d200879d4ee.png)
![selection_025](https://cloud.githubusercontent.com/assets/200945/19518490/61bcb82e-95ff-11e6-905e-7d753876ebba.png)
![selection_026](https://cloud.githubusercontent.com/assets/200945/19518491/61c4175e-95ff-11e6-8c2f-10772c80eed7.png)

I recently switched to LXQT from KDE and I have realized that some windows don't have minimize buttons. They all have rollup, unroll buttons which shrink the form to the size of the titlebar only and restore it when unrolled.

Is there something about the forms themselves that result in LXQT not showing the minimize button or are some configuration settings required in LXQT itself for minimize buttons to be displayed on all the applicable forms?

**Comment by stefonarch** [comment]
These buttons are controlled by the windowmanager in use, so check kwin configuration in KDE systemsettings or obconf for openbox, probably you are using one of them.

**Comment by pmattern** [comment]
Please state which windows are affected, whether it's all, only a particular kind or whatever. Also, name the window manager you're using.

**Comment by vonHabsi** [comment]
@stefonarch How do I check which window manager I am using? I am using LXQT so assume that it must be the LXQT default. It is the one I choose when I logged on.

@pmattern It is hard to decide what kind of Windows they are, but under KDE they could all be minimized. Some of them are GTK2 programs are compiled by myself. I have to look into them further.
Perhaps they were compiled with some settings which don't allow them to be minimized properly.

**Comment by stefonarch** [comment]
Check in LXQt Configuration > Session settings, there you choose your window manager, probably it's openbox.

**Comment by pmattern** [comment]
> How do I check which window manager I am using?

It's selected and hence indicated in GUI [LXQt Session Settings](https://github.com/lxde/lxqt-session#lxqt-session-settings).
From the command line you may simply run `ps aux | grep -Ei 'kwin|openbox|xwin'` assuming it's either KWin, Openbox or Xfwm, the expression stating the window managers may have to be extended with others available on your system. Or you install [wmctrl](http://tripie.sweb.cz/utils/wmctrl/) and run `wmctrl -m`.

> It is hard to decide what kind of Windows they are [...]

Well, I was asking in order to try and reproduce your findings and to figure out whether it's an issue at your side, which seems pretty likely so far, or something we'll have to look into.
So a single sample application which is affected at your side would really be helpful.

**Comment by pmattern** [comment]
After having another look at your screenshots it's pretty obvious you're using Xfwm4, the window manager of Xfce. This in turn is most likely due to running Debian where this window manager is set as default.
Xfwm is indeed hiding the icon to minimize in certain kinds of windows, among other e. g. those of all tools `lxqt-config-*` and the panel's configuration dialogue. At first glance it's not possible to change this behaviour. Regarding its configuration you may want to have a look at the [section](https://github.com/lxde/lxqt/wiki/ConfigWindowManagers#xfwm4) about this window manager in our wiki.
So if I'm not mistaken you have to use a window manager other than Xfwm if you want this icon to be always visible. Notes about this can be found in the wiki page linked above, too.

Closing due to lack of feedback and as it's apparently a non-issue.
