### ISSUE TITLE
plugin-mainmenu: option to clean search field should be available

### ISSUE THREAD

**Issue by Gibbz** [lxde/lxqt#1254]
##### Expected Behavior
The application menu stores the last search. There should be an option for it not to do this, as usually I only need to launch one instance of an app, and having to clear the search field each time I run an app is clumsy.

##### System Information

* Distribution & Version: qtubuntu 16.04
* Kernel: 4.4
* Qt Version: 
* liblxqt Version:  
* Package version:  0.10

**Comment by tsujan** [comment]
Some users prefer it to remember the last search, some don't. I agree that an option would be handy.

**Comment by pmattern** [comment]
Certainly a reasonable suggestion.

Maybe we could address another long-standing related problem while at it: when plugin-mainmenu is opened by keyboard shortcuts, the focus is mandatory within the search field, so using keys to navigate the menu doesn't work any longer (https://github.com/lxde/lxqt-panel/pull/309#issuecomment-203618497).
Note there's another problem due to which plugin-mainmenu as a whole sometimes doesn't receive focus at all if opened by keyboard shortcuts (#401). Obviously this makes dealing with an optional commit to address which object within the plugin is focussed upon opening the plugin by shortcuts more difficult.

**Comment by palinek** [comment]
...implemented in lxde/lxqt-panel#393
