### ISSUE TITLE
repaint artifacts, graphical artifacts

### ISSUE THREAD

**Issue by Timgit2** [lxde/lxqt#1264]
For the first minute or so the desktop is fine. as soon as a program is opened and used for a short period, say dolphin, the artifacts begin. I thought it had something to do with KDE5's desktop behaviors, but after disabling them, nothing changed.  The process isn't permanent, it doesn't create artifacts that stay in place. Unless going from minimized to maximized then generally the mouse has to be moved over the object to render t properly, or the window has to be moved around. While dragging a window the repaint artifacts stutter and the whole window does as well. Sometimes when done moving a window it won't have certain parts rendered completely until clicking on and dragging over the window.

Upon restart, the issue is resolved, but, begins again after repeating the above.

i had an earlier build that was fine, i hadn't done any updates for about a month. upon accepting the most recent updates this issue arose.  However, i will say it is the same without KDE installed, i did a fresh install and was having similar issues but more severe when i had LXDE installed also, but not KDE.

##### System Information

* Debian testing
* Kernel: 4.9.6-3
* Qt Version: 5.7.1+dfsg-3+b1
* liblxqt Version:  0.11.1-1
* Package version: 0.11.1-1

**Comment by pmattern** [comment]
Just to avoid misunderstanding and as you don't explicitly state it: the problem does affect LXQt sessions?

That aside this pretty much sounds like some compositing issue. So please let us know which window manager and/or compositor you are using. Information about graphics hardware and driver would be useful, too.

**Comment by Timgit2** [comment]
Yes under LXQt

Right after i posted my initial comment i thought about changing the window manager. Both the x11 and wayland versions of kwin produced the issue. xfwm4 doesn't produce this issue. multiple log in/outs after changing the window managers and trying to reproduce the issue under those three window managers.

AMD c-60 APU (radeon HD) on acer aspire one 722
xserver-xorg-video-ati 1:7.8.0-1+b1
firmware-amd-graphics 20161130-2
xserver-xorg-video-amdgpu 1.2.0-1+b1

**Comment by pmattern** [comment]
Right now Wayland support of LXQt is still facing a lot of problems, see e. g. the discussion which took place recently in #10. I suggest we don't consider Wayland with regards to this issue.

That aside we are a step ahead now and here are some more steps you could take to further narrow down the problem:
* Figure out which of the two DDC drivers ati and amdgpu is supporting your hardware and remove the unneeded one. To my knowledge these are never used in parallel so we should rule out any problem due to having them installed in parallel.
* As for Xfwm4, make sure compositing was enabled when you did not see the problem.
If unsure, you can check this in tab "Compositor" of "Window Manager Tweaks" (binary `xfwm4-tweaks-settings`).
* Check whether the problem is affecting Openbox plus Compton as well.
Compton can be launched from the "LXQt Session Settings" (binary `lxqt-config-session`) - Basic Settings. You may want to tweak some settings in ComptonConf (title "Special Effect Settings", binary `compton-conf`) to make sure it's active.
* Check whether the problem is manifest in Plasma sessions.
* Check whether the problem persists, when compositing in KWin is disabled.
This can be tweaked in KDE System Settings - Hardware - Display and Monitor.

**Comment by Timgit2** [comment]
sorry for the long delay.  Anyhow, figured out the issue, actually incredibly easy fix. Found that this is a KDE independent issue.  With a fresh install and choosing LXDE there was no issue, and a fresh install with just KDE the issue remains.  As it turns out, this is fairly common, there is an option to check in the compositor settings, "tearing prevention vsynce" and select never instead of automatic and the issue is resolved.

thanks for the help.  

Also, just for finalization, under LXQT i was unable to open compositor or window manager tweaks, and did not have Compton installed.
