### ISSUE TITLE
Icon padding discrepancies in panel

### ISSUE THREAD

**Issue by hughwilliams94** [lxde/lxqt#1336]
The icon padding differs between panel items and the individual items in the System Tray which is visually odd when they are aranged next to each other. Is this something that could be adjusted to give more uniform spacings?

![screenshot_20170813_214618](https://user-images.githubusercontent.com/15379654/29253316-e63ccc7c-8070-11e7-9cfe-e59abee413b5.png)

**Comment by agaida** [comment]
if we would know about what and which version we talk - we would. The issue template is there for a reason.

**Comment by hughwilliams94** [comment]
Sorry about that, have updated accordingly.

**Comment by tsujan** [comment]
The "spacer" is there and is configurable.

**Comment by hughwilliams94** [comment]
I am talking about spacing between each icon in the system tray widget

**Comment by tsujan** [comment]
> I am talking about spacing between each icon in the system tray widget

I meant that for grouping tray icons so that they wouldn't be mixed with other ones.

Otherwise, the spacing depends on the *theme* you use. The following image shows the spacing between the vertical tray icons of my panel after I added a ridiculous line like `margin: 10px 1px 10px 1px;` to an appropriate place (each theme may have a different place for that):

![tray](https://user-images.githubusercontent.com/981076/29253660-7d69fdf0-8098-11e7-88cc-8ae4dd2afc12.png)

**Comment by hughwilliams94** [comment]
@tsujan Thank you very much, I was able to adjust it by adding a tray section to the system theme which I was using, did exactly what I wanted it to

**Comment by tsujan** [comment]
You're welcome!

> I was able to adjust it by adding a tray section

For my theme, the proper place was inside this block:
```
LXQtPanel[position="Left"] Plugin > QToolButton, 
LXQtPanel[position="Left"] Plugin > QWidget > QToolButton > QWidget > QToolButton,
LXQtPanel[position="Left"] Plugin > QWidget > QToolButton {
...
margin: ...;
...
}
```
However, there are other ways too; QSS is flexible.
