### ISSUE TITLE
lxqt-config-appearance "Colorize icons based on widget style (palette)" seems to be not respected

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1445]
##### Expected Behavior
i mark or unmark this in lxqt-config-appearance and if the icon theme support it the icon color change - works fine in a running system

##### Current Behavior
i set this property to my preferred value, the desktop looks fine - log out, login the setting is not respected anymore.

##### Possible Solution
no clue.

##### Steps to Reproduce (for bugs)
1.  install the papirus theme in arch or debian 
2. have latest git installed
3.  deactivate setting
4.  log out, log in

##### System Information
* Package version:  latest git, Qt 5.9 debian Qt 5.10 arch

![screen02](https://user-images.githubusercontent.com/1162845/36080478-14b8fb70-0f91-11e8-9b21-2145d9e951ed.jpg)
^^ not wanted
![screen04](https://user-images.githubusercontent.com/1162845/36080479-1dfbbc86-0f91-11e8-90b9-5cbcbec60ba2.jpg)
^^ wanted

so it works basically, but not after relogin

**Comment by agaida** [comment]
btw - the setting is saved and loaded fine

**Comment by tsujan** [comment]
Will look into it after finishing some things in FP.

**Comment by agaida** [comment]
Thanks a lot - ok, on the positive site i have an up-to-date arch now :D

**Comment by tsujan** [comment]
BTW, it happens here too. If I uncheck the option, it'll remain unchecked after logging out and in but without having an effect.

**Comment by tsujan** [comment]
I found a little time to take a quick look at the code(s). The problem was in `lxqt-qtplugin`: there was no way for `LXQtPlatformTheme` to load the colorizing setting on startup -- it just read it from the config file and waited for it to be changed.

The colorizing setting can be loaded at `LXQtPlatformTheme::createIconEngine()`. I tested and it worked. Now, I should have some sleep; will make a PR later.
