### ISSUE TITLE
World clock plugin translation problems

### ISSUE THREAD

**Issue by kubanecxxx** [lxde/lxqt#422]
The plugin source directory is different then name of plugin in cmake. Plugin source is in "plugin-worldclock" and plugin name in cmake is "panelworldclock".The translator has to care about the right .ts filename and he may feel confused.

**Comment by jleclanche** [comment]
@kuzmas @luis-pereira ping

**Comment by luis-pereira** [comment]
@kubanecxxx @jleclanche @kuzmas There are other plugins as well. We can safely drop the panel in "panelworldclock" because:
1) the lib is installed to prefix/lib/lxqt-panel
2) the .qm is installed to prefix/share/translations/lxqt-panel/plugin-name
3) .desktop files is installed to prefix/share/lxqt/lxqt-panel/

I will unify the naming after merging any pending translation stuff.

**Comment by kuzmas** [comment]
@luis-pereira <https://github.com/luis-pereira> I've noticed that there are
some plugins have "panel" prefix, but was not sure whether it's safe to
remove. If you're sure - I'm all for unification.
