### ISSUE TITLE
lxqt-panel: removable media menu closes on clock update

### ISSUE THREAD

**Issue by novist** [lxde/lxqt#490]
Whenever clock info (minutes/days/years/hours/**seconds**) change removable media menu is closed. Meaning if we have clock showing seconds it is not possible to use removable media panel widget because it is closed in one second since opening.

**Comment by jleclanche** [comment]
Works fine here. You sure it's on clock update?

**Comment by novist** [comment]
Pretty sure. If i enable showing seconds like i said menu closes near-instantly. If i disable showing seconds then menu remains open until minute flips. I can notice small delay though. First menu closes then ~500ms later minutes number flips.

**Comment by palinek** [comment]
Just tried that...for me menu is closed only in case when:
- panel is on top/botom of the screen
- menu is shown on top/bottom of the clock widget
- clock is configured so that it's content does not fit into panel height
It seems for me that the not-shown portion of clock widget colides with the menu.
