### ISSUE TITLE
Linking liboobs

### ISSUE THREAD

**Issue by temudschin** [lxde/lxqt#495]
I think, the linking of liboobs library is missing the OOBS_LIBRARY_DIRS variable in:

 lxqt-admin/lxqt-admin-time/CMakeLists.txt

and

lxqt-admin/lxqt-admin-user/CMakeLists.txt 

resulting in a linker error, if liboobs is not installed in a standard lib path.

I would propose to add:

link_directories( ${OOBS_LIBRARY_DIRS} ) 
in both CMakeLists.txt files.

**Comment by jleclanche** [comment]
FWIW Im not a fan of using liboobs at all. It's not in the main repos of several distros (including arch), and it's perl scripts for god sake.

**Comment by PCMan** [comment]
At some time we have to develop a replacement for it.
Liboobs can still be retained to support other OSes, such as BSDs.
For Linux, we can develop our own code and some stuff can be supported using systemd.
The date/time tool only needs to call timedatectl.
AccountService might handle user management but I believe that it will be dropped since few people are using it and it's not quite active. Alternatively, @jleclanche you can develop some python scripts.

**Comment by PCMan** [comment]
The real problem is, how to use polkit properly since we don't want to run all admin apps with root.
I don't know how to do polkit programming in python so @jleclanche maybe you can do it.

**Comment by jleclanche** [comment]
We could simply not have bsd suppot in lxqt-admin. It's a fairly minor component...

**Comment by heliocastro** [comment]
We don't have liboobs since Fedora 20, so this is a reason we do not have
the package yet on our distro.

**Comment by City-busz** [comment]
I recommend to use [systemd-timedated] (http://www.freedesktop.org/wiki/Software/systemd/timedated/) and [AccountsService] (http://www.freedesktop.org/wiki/Software/AccountsService/) D-Bus interfaces as backend. Then you don't need to care about polkit, everything is handled by these services.

**Comment by PCMan** [comment]
Yes, that's indeed a good idea and I intended to do that previously.
However, I'm not sure how good AccountService is.
Does anyone has experience on that? Or @City-busz  are you willing to provide patches?

**Comment by Vladimir-csp** [comment]
The way I see it, AccountService is a service primarily used in GNOME. Somebody dragged it into lightdm just [because it was used in GDM](https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/823718). There are a couple of hanging [bugs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690898) here and there in which 'non-DE' users, myself included, asked for lightdm to be usable without GNOME dependencies such as AccountService. They are partially solved, partially hanging (lightdm [has some issues](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765077)). So, from user/admin perspective (at least from mine and those who supported AccountService independence in lightdm), AccountService is something that solves nothing while runs a redundant system daemon which task can be accomplished by simple static config files or their cache.

**Comment by City-busz** [comment]
@PCMan sorry, but I don't have any experience with Qt programming.

**Comment by agaida** [comment]
Hi, i need to bump this issue a little bit, reason: there are plans to remove liboobs from debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821864

**Comment by jleclanche** [comment]
@agaida It seems unlikely we would manage to get this done by next release. My suggestion is dropping lxqt-admin from debian.

**Comment by agaida** [comment]
we will do so in the worst case - but we all know, that debian is "very fast" in removals - i think i should ask maintainers for a time frame

**Comment by LStranger** [comment]
>Hi, i need to bump this issue a little bit, reason: there are plans to remove liboobs from debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821864

You may relax - as long as I am a maintainer of liboobs in Debian, I will
keep it there, it's not a decision of Michael Biebl or GNOME maintainters
team. It was wrong from my side to leave them in Uploaders list, I will
fix that very soon and liboobs will stay as long as it works, and I would
keep it working since it is only way to get some functionality if you are
not in KDE nor in GNOME.

**Comment by agaida** [comment]
@LStranger - good to know, i'm relaxed now :D

**Comment by szlin** [comment]
It seems like liboobs will keep in Debian archive; therefore,  my assumption is that #821864 should be closed without any action.

**Comment by agaida** [comment]
@szlin: as you see, liboobs is not in Fedora anymore and we really are no liboobs fans - so if you like to work on this nobody would hinder you i guess. :)

**Comment by PCMan** [comment]
Well, please take a look at the "systemd" branch.
Date time management is now handled with systemd. This part is already finished and needs some testing. There is also a "user" branch, which is going to use AccountService for user management, but it's still a work in progress. With these two changes, we no longer require liboobs.
I'm working on my master thesis now so don't have time for LXQt this month. Later I'll finish this part.

**Comment by jleclanche** [comment]
@PCMan We should do a delayed release of lxqt-admin then. We don't release it alongside 0.11; we wait until the systemd branch is merged.

**Comment by agaida** [comment]
+1

**Comment by palinek** [comment]
> Well, please take a look at the "systemd" branch.

@PCMan Are you using the systemd's CLI (and not the DBus interface) because of access ritghts?

**Comment by palinek** [comment]
done in lxde/lxqt-admin/#34
