### ISSUE TITLE
Replace XFitman in lxqt-panel by kwindowsystem

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#497]

**Comment by palinek** [comment]
Just a quick summary of the state:
- XfitMan is used only in plugin-tray
- for "xembed" windows tried to replace using of XfitMan::Resize/MoveWindow by NETRootInfo::moveResizeWindowRequest => no luck and it seems that NETRootInfo object fails to move/resize non-top-application window
- all use of XfitMan is just caching xlib's Atoms (other uses are just direct map to xlib calls)
- we are not able to completely remove the xlib dependency because of usage xembed protocol
- xembed is deprecated and we will create a new "notification" plugin (lxde/lxqt#359)

... so leaving this untouched for now

**Comment by paulolieuthier** [comment]
Yeah, we can't remove this dependency. We'll need XfitMan for the tray plugin forever, to be able to support X11. However, that should become optional, for Wayland won't use it. The new notification spec, which [is being worked](https://github.com/equeim/lxqt-panel-plugin-snw) for lxqt-panel by @equeim, uses Xembed as fallback, as discussed in #359.

IMO, we should work to make @equim's plugin used by default in 1.0.

Btw, `NETRootInfo::moveResizeWindowRequest` is meant to be used by window managers.

**Comment by palinek** [comment]
@paulolieuthier, @equim do you, guys, have something in the new plugin I can help with?

**Comment by paulolieuthier** [comment]
Well, there is a lot to do. It's good to have you with us now :smile:. If want to take this one, move @equim's plugin to lxqt-panel and try to merge it with our current plugin. The current plugin must be used only when on X11 and only when the new plugin can't work (thus, fallback). Feel free to ask for help, ping on irc etc.

**Comment by palinek** [comment]
@paulolieuthier do you want to merge the new plugin into the old one? Because @jleclanche  proposed to have old and new one as separate plugins.

**Comment by paulolieuthier** [comment]
According to [PCMan](https://github.com/lxde/lxqt/issues/359#issuecomment-61419010), the plugin should fallback to Xembed when needed. But there is no Xembed in Wayland, so that should be defined at compile time. @PCMan, @luis-pereira, @jleclanche what do you guys think?

**Comment by jleclanche** [comment]
I'm strongly in favour of splitting the old and new methods into two different plugins. The status notifier spec is about a lot more than the xembed systray.

**Comment by paulolieuthier** [comment]
> The status notifier spec is about a lot more than the xembed systray.

@jleclanche what do you mean?

**Comment by paulolieuthier** [comment]
> I'm strongly in favour of splitting the old and new methods into two different plugins.

I have no problem with that.

**Comment by PCMan** [comment]
FYI:
http://www.notmart.org/misc/statusnotifieritem/backwards-compatibility.html
Not a strong requirement, but the spec indeed has some suggestions about
xembed as fallback.
If you do this, XEMBED becomes a "subset" of the new implementation then
it's better to do it in the same plugin.
However, I'm fine with making them separate plugins since XEMBED Is really
problematic.
Having no XEMBED support is also acceptable since status notifier becomes
popular nowadays.

**Comment by paulolieuthier** [comment]
I'm closing this, as XfitMan is (and always will be) used in lxqt-panel's tray plugin. But the tray plugin it self is optional, just like any other plugin. So lxqt-panel will be ready for Wayland when KWindowSystem is.
