### ISSUE TITLE
is liblxqt-config-cursor really needed?

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#498]
it would ease the packaging for debian if liblxqt-config.cursor would be not a library like the other parts of lxqt.config

liblxqt-config-cursor
lxqt-config-appearance
lxqt-config-file-associations
lxqt-config-input
lxqt-config-monitor

**Comment by jleclanche** [comment]
Hu?

**Comment by agaida** [comment]
all other parts of admin aren't libraries - only liblxqt-config-cursor remains a library - and i ask myself for a reason. For debian that means handle lintian stuff like:
<pre>
lxqt-config: package-name-doesnt-match-sonames liblxqt-config-cursor
lxqt-config: shlib-without-versioned-soname usr/lib/liblxqt-config-cursor.so liblxqt-config-cursor.so
lxqt-config: pkg-has-shlibs-control-file-but-no-actual-shared-libs
</pre>
which can bite us - creating and maintaining packages for a not needed library isn't that funny. Eventually creating symbols for 10+ architectures isn't funny to.

**Comment by PCMan** [comment]
It's used in both mouse configuration and appearance configuration, which
are in different programs.
That's why it's a library.
Keeping it this way make it easy for users to find the options.
As mouse cursor is related to input device configuration and it also affect
look & feel, I believe that the current design is reasonable.

**Comment by agaida** [comment]
Ok, thanks for the clarification - i'll make packages for that. That leaves only the so-name versioning open i think. Will create a new bug later.
