### ISSUE TITLE
Fresh lxqt instances do not have a theme selected in 0.9

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#500]
I'm guessing this has to do with the re-capitalization of themes? @paulolieuthier @intialonso

**Comment by pmattern** [comment]
Problem affects recent Git code as well.

Your guess regarding capitalization seems very likely to me: E. g. the wallpaper image's path at Desktop Preferences - Tab "General" - Wallpaper image file is using lower case exclusively as long as no theme has been selected but starts using upper case as well once a theme has been chosen in LXQt Appearance configuration.

**Comment by intialonso** [comment]
I have made no changes in the themes in the last days, the problem must be somewhere else.

**Comment by jleclanche** [comment]
@paulolieuthier I think this is caused by the themes being capitalized. There should be a difference between a theme's *name* and its place on the disk.

**Comment by paulolieuthier** [comment]
The capitalization I did was in the labels in lxqt-config-appearance, check it out: lxde/lxqt-config@c05e5809cd1b18b27e4f7f139d1ef7fb939b3728. The problem is that the folders' names were capitalized as well (lxde/lxqt-common@0ad2b72d108937b48c8b63b4f1951595f69a1c2a), and the [default config](https://github.com/lxde/lxqt-common/blob/master/config/lxqt.conf) for theme is `frost`, lower case.

**Comment by jleclanche** [comment]
@paulolieuthier can we move them to be lowercased, and in the settings always force lowercase? (eg be backwards compatible and interpret `Frost` as `frost`. This also happens to be a good idea in general imo)

**Comment by paulolieuthier** [comment]
Agreed. I'll do it.

**Comment by paulolieuthier** [comment]
@jleclanche, please update lxqt-common and lxqt-config and test it.
