### ISSUE TITLE
Disable opacity slider in panel config if compositing is not available

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#514]
And add a note: "Compositing is required for panel transparency."

**Comment by Vladimir-csp** [comment]
Compositing can be switched on and off at will, so why disable the slider? Only add note when compositing is off, but leave the ability to set transparency all the time.

p.s. No pseudo-transparency?

**Comment by palinek** [comment]
Why disable it? We are not disabling the "dark" theme which also set the background of panel to semitransparent.
IMHO we should only set the default opacity of background color to 1 (no transparency) and put the note "Composiging..." somewhere.

**Comment by paulolieuthier** [comment]
For future reference: we can know if compositing is active easily [using KWindowSystem](http://api.kde.org/frameworks-api/frameworks5-apidocs/kwindowsystem/html/classKWindowSystem.html#a8693714dc9f40b337fa6b63896e25d78).

**Comment by jeremywh7** [comment]
>p.s. No pseudo-transparency?
Is this in reference to what LXDE does?  I switch b/t it and LXQt on this machine, and in LXDE, I have it set so that the background image shows thru semi-transparently, and I only Openbox with LX*.  LXQt can't do this; so I wonder if that to what this refers?  Is there not an intent to support what LXDE does in that regard?
