### ISSUE TITLE
Do not warn about missing battery when battery watcher is enabled

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#516]
If the battery watcher is enabled, we should display a "missing battery" icon in the place of the usual one, instead of being loud about it. The user can then remove the icon easily if needs be.

**Comment by palinek** [comment]
Maybe this is also the opportunity to switch from all QDbus* handling to ```KF5::Solid``` for battery handling...

**Comment by jleclanche** [comment]
Yes, agreed.

**Comment by paulolieuthier** [comment]
There is already a branch in lxqt-powermanagement for that, I'm working on it.

**Comment by palinek** [comment]
@paulolieuthier just had a quick look at your commit ee8f48c4a7cd1a00743433b6ce0481c40d0a43e8. I don't know if there are machines where batteries can be removed/added while running, but I would suggest to store the batteries as ```Solid::Device``` because AFAIK from ```Solid::Battery*``` you are not able to get back the device UID which would be good to have for all the signals handling (e.g.: ```deviceAdded```, ```deviceRemoved```).

**Comment by paulolieuthier** [comment]
@palinek good point. That will come later.
