### ISSUE TITLE
Can't disable multiple battery icons in panel

### ISSUE THREAD

**Issue by pertplus** [lxde/lxqt#535]
The panel now shows two icons for battery on my laptop, one for the main battery and one for my wireless mouse. In power management I can't disable the mouse battery icon, I have to disable both or keep both. I think you should be able to choose which icons are shown. Incidentally, the battery icon for the mouse doens't work, it just always shows 100% (with min/max charge listed as 0).

**Comment by surlykke** [comment]
@pertplus : Can you check if 430fd963 fixes?

It should give the behavior we had when interfacing directly to UPower: Only show batteries that act as a power supply.
I can't test as I don't have a mouse that reports battery levels.

br. Chr

**Comment by paulolieuthier** [comment]
@pertplus it's in master.

**Comment by pertplus** [comment]
Would like to help but I don't know what I'm supposed to do! Where do I get 430fd9693? That's a version of lxqt-panel, or ?  I'm sorry!

**Comment by paulolieuthier** [comment]
@pertplus don't worry, it's ok. First, I suggest that you install a Github Notifier extension for you browser, so you know when someone talks to you. 430fd9693 is a commit. See it here: lxde/lxqt-powermanagement@430fd963fbe4f16d9da9f60b67ffd14d9e1d49b0. The commit is in the master branch, which means you only have to update lxqt-powermanagement to get it and test it.

How did you install lxqt? Have you updated it since then? Can you still reproduce the bug? If you have any question, feel free to ask.

**Comment by pertplus** [comment]
Updating lxqt-powermanagement solved the problem, thanks. I'm using a user package from the Arch Linux AUR.

**Comment by paulolieuthier** [comment]
Great news. Thanks for your help.
