### ISSUE TITLE
desktop_is_home_dir not eligible

### ISSUE THREAD

**Issue by MttCastelli** [lxde/lxqt#541]
I've set it in LXQt Desktop preferences so that user-dirs.dirs looks like this:

```
XDG_DESKTOP_DIR="$HOME"
XDG_DOWNLOAD_DIR="$HOME"
XDG_TEMPLATES_DIR="$HOME/.Modelli"
XDG_PUBLICSHARE_DIR="$HOME"
XDG_DOCUMENTS_DIR="$HOME/Documenti"
XDG_MUSIC_DIR="$HOME/Musica"
XDG_PICTURES_DIR="$HOME/Immagini"
XDG_VIDEOS_DIR="$HOME/Video"
```
So, LXQt settings correctly modify the file, but do not follow the guidelines in practice, couse desktop keep being empty instead of shwing user folders... 

Seems I can't achieve my preferred behaviour, it's a curse!
(Lubuntu vivid + lubuntu-dev PPA + lxqt-metapackage - both qt4 and gtk stacks removed as possible)

#pcmanfm-qt #lxqt-session

**Comment by pmattern** [comment]
I'm not 100% sure I understood what you want but setting a directory to $HOME is meant to disable it, see [Specification](http://www.freedesktop.org/wiki/Software/xdg-user-dirs/), section "Settings", "Note: To disable...".
So things like using $HOME as the directory that's displaying the desktop isn't covered by the specification.

**Comment by MttCastelli** [comment]
But it's exacty what I want: disabling Desktop directory and delete it so that desktop is home, as specification report. If you disable Download dir, for example, files will be downloaded in /home/user... I want my desktop to show folders as they are in /home/user.

**Comment by MttCastelli** [comment]
@pcmanfmMay I ask if it is pcmanfm-qt to handle the desktop, so to be sure where the bug is and add the right lavel too?

I've found that if I do set Desktop folder is  /home/matteo trough desktop preferences menu, it correctly edit user-dirs.dirs. But then pcmanfm-qt keep displaying Desktop between places category (on the lft), and if you try to select thisitem, it points to  /home/matteo/app, directory that does not exist.

**Comment by headbank** [comment]
MttCastelli, I found this posting due to having the same problem, so thanks for bringing it up in public - and thanks pmattern for revealing the reason. I never would have considered this, but somehow it's unsurprising that freedesktop is behind it :(

Anyway, as far as getting the homedir to be shown on the desktop, I've found this works:

XDG_DESKTOP_DIR="$HOME/."

Hope it helps.

**Comment by MttCastelli** [comment]
@headbank thank you so much, I finally get this behaviour and I really apreciate.

However I still think it's a #pcman-qt problem.

**Comment by headbank** [comment]
I have to disagree there: PCMan is making a desktop, so you can't really blame him for following the freedesktop spec. The spec is at fault here, so blame freedesktop. I intend to ;)

**Comment by MttCastelli** [comment]
@headbank sorry but I can't get this: freedesktop spec are the same in GNOME and KDE, for example, and they are also the same if you use pcmanfm ver. 1.2.x (gtk); specifications say that you can disable desktop_dir and use your home to make the desktop, and so it is in GNOME, KDE and with pcmanfm too. It's just pcmanfm-qt to refuse this setting.

I'm not a coder and I can't see under the hood, I'm just trying to use coarse logic...

**Comment by headbank** [comment]
I'm pretty much the same as you describe yourself, so don't worry, I'm not claiming any authority myself ;)

I guess the "spec" is pretty ambiguous anyway: what does the desktop environment infer by one of these dirs being "disabled"? You might say (as was my interpretation above) that "XDG_DESKTOP_DIR is disabled" should be taken as "There isn't one". Assuming that, then lxqt is actually the *first* desktop to get it *right* by not showing any folder's contents on its desktop; all the others are violating the spec by showing anything.

Alternatively, if you read it as "It's my homedir, as stated" (which I must admit is hopefully the correct interpretation), then you're correct that lxqt is the only one doing it wrong.

On reflection I think that fits better: if a dir isn't specified ("disabled" - which probably only refers to the auto-creation of the folder), then it makes sense for it to default/fallback to the homedir.

**Comment by pmattern** [comment]
Interestingly enough this thread had taught me that I was probably misunderstanding the meaning of "disabled" for years, too.
Like you, I had always thought, "disable" means "doesn't exist", "isn't set at all" or something. But indeed it seems to mean "fall back to using $HOME".
I still think the specification's documentation is pretty misleading here.

**Comment by paulolieuthier** [comment]
@MttCastelli have you seen pcmanfm-qt desktop's advanced tab's options? You can set the desired directory there. And yes, it is pcmanfm-qt that handles the desktop icons in lxqt (by default).

**Comment by MttCastelli** [comment]
@paulolieuthier please try yourself to set 'Desktop folder' to your home in pcmanfm-qt desktop's advanced tab's options, and you'll not see any changes: no folders in your desktop and the Desktop place in pcmanfm-qt side panel will give you a non sense path (such as /home/matteo/_on, in my case.)

@headbank I'm happy to agree with you now. And also, please don't assume I'm worried just because my avatar is :)

**Comment by paulolieuthier** [comment]
@MttCastelli I can reproduce the bug as well. It's a regression, this feature worked before. Does it work for you if you kill pcmanfm-qt and restart it?

**Comment by paulolieuthier** [comment]
This is not a bug in pcmanfm-qt, it's a bug in libfm. @PCMan, `fm_path_get_desktop` does not update after changing the desktop folder (which is done correctly). Any pointers?

**Comment by LStranger** [comment]
>This is not a bug in pcmanfm-qt, it's a bug in libfm. @PCMan, `fm_path_get_desktop` does not update after changing the desktop folder (which is done correctly). Any pointers?

This is not a bug but a feature. We got bugreports before from people who
tried to clear their desktop removing everything but they've set it to
$HOME so eventually they've lost all their files. There is no other way
to prevent this to happen but deny setting desktop to $HOME which was
done few years ago and everyone were happy with that until you raised
your issue. I believe that you just doing it wrong as you can always add
links to your desktop simply dragging desired items from $HOME to your
desktop, and setting XDG_DESKTOP_DIR and XDG_DOWNLOAD_DIR to the same dir
is completely valid case. It works in original PCManFM, and if it does
not work in the pcmanfm-qt then it's definitely a bug in pcmanfm-qt.
Thank you very much.

**Comment by LStranger** [comment]
Also I would say if you want exactly your behavior (using the $HOME for
desktop) then you can create some (preferrably hidden to not annoy you)
symlink like this:
$HOME/.Desktop -> .
and then set XDG_DESKTOP_DIR="$HOME/.Desktop". It should work as well.

**Comment by paulolieuthier** [comment]
@LStranger I'm not sure I understood what you said. The problem is that pcmanfm-qt correctly changes `XDG_DSKTOP_DIR` in `~/.config/user-dirs.dirs` to the desired place, but `fm_path_get_desktop()` does not get the updated directory. If I restart pcmanfm-qt, it works.

Should it stop using `fm_path_get_desktop()` and use its own parser of the config file?

**Comment by LStranger** [comment]
>@LStranger I'm not sure I understood what you said. The problem is that pcmanfm-qt correctly changes `XDG_DSKTOP_DIR` in `~/.config/user-dirs.dirs` to the desired place, but `fm_path_get_desktop()` does not get the updated directory. If I restart pcmanfm-qt, it works.

>Should it stop using `fm_path_get_desktop()` and use its own parser of the config file?

Well, original post was about the XDG_DESKTOP_DIR="$HOME" setting (i.e.
setting Desktop to Home) and I have commented that issue being feature,
not bug.

But original post issue is a different issue from one noticed by you and
in regard of following changes in the ~/.config/user-dirs.dirs file, it
cannot be done unfortunately since API does not allow reloading it, that
can lead either to memory leak or to application crash, so only safe way
to update the path is to restart application (pcmanfm-qt). Well, it is
possible to implement reloadable API instead of fm_path_get_desktop() but
that will require some number of changes to use that new API and cannot
be done before ABI update (so not earlier than in version 1.3 of libfm).

**Comment by paulolieuthier** [comment]
@LStranger I get it, thanks.

**Comment by MttCastelli** [comment]
You should really fix this with 0.10 release: the workaround to set '/home/user/.' in Desktop preferences works no more for the new Locations menu in Session settings, have to edit 'user-dirs.dirs' files manually. But the most is that if you set desktop as home dir in Locations everythings crashes, both te desktop and pcmanfm-qt every time you click on Desktop shortcuts in Paces.

Once another, desktop_is_home_dir is the pure Unix behaviour, we do not need to monkey imitating Windows, and anyway we could always have the way to choose.  Regards

**Comment by pmattern** [comment]
> in Desktop preferences works no more for the new Locations menu in Session settings, have to edit 'user-dirs.dirs' files manually. 

There's some usability issue due to which setting `/home/<user>` doesn't work at once, see third paragraph in https://github.com/lxde/lxqt/issues/780#issuecomment-154203484.
But aside from this minor drawback everything is working as expected here: select "Locations" in left pane of `lxqt-config-session`, clear "Desktop" by hitting the icon at the form's right end, leave `lxqt-config-session` confirming the dialog about the need to restart → `~/.config/user-dirs.dirs` states `XDG_DESKTOP_DIR="/home/<user>"` and this very setting is even applied at once.
Recent VCS checkouts of all LXQt components on Arch Linux i686.

> But the most is that if you set desktop as home dir in Locations everythings crashes, both te desktop and pcmanfm-qt every time you click on Desktop shortcuts in Paces.

Can't reproduce crashes but something seems to be rotten indeed.
@PCMan @luis-pereira 
PCManFM-Qt doesn't realize if `lxqt-config-session` is used to set `XDG_DESKTOP_DIR` in `~/.config/user-dirs.dirs` to something different than the default values like `$HOME/Desktop`. As a consequence selecting \<desktop folder like "Desktop"\> in PCManFM-Qt's left pane in places view yields an empty right pane besides XDG_DESKTOP_DIR is working as expected, sometimes strange special characters like `/home/peter/�` can be seen in the address bar and according to @MttCastelli crashes may happen.
Any thoughts on this? Maybe a problem related to lxde/pcmanfm-qt@a16f7e7?

> Once another, desktop_is_home_dir is the pure Unix behaviour, we do not need to monkey imitating Windows, and anyway we could always have the way to choose. Regards

Utterly superfluous remark. Since we realized the valid purpose of this issue no one wanted to prevent using $HOME as desktop directory.

**Comment by luis-pereira** [comment]
@pmattern It's not related to https://github.com/lxde/pcmanfm-qt/commit/a16f7e7. Just checked, it happened before. It's a caching issue within libfm-qt or it's dependencies. If one restarts  pcmamfm-qt instances (including the desktop manager) it will read the Desktop setting Ok.

**Comment by pmattern** [comment]
@luis-pereira 
> If one restarts pcmamfm-qt instances (including the desktop manager) it will read the Desktop setting Ok.

True. Didn't consider this earlier as setting XDG_DESKTOP_DIR in `lxqt-config-session` takes effect at once with regards to the desktop itself.

@MttCastelli 
Looks as if using $HOME as desktop directory including the two problems you stated in your previous post is working as expected with latest VCS code after starting another session (which is what `lxqt-config-session` recommends upon exiting).
You may have another look and report back if still something seems to be wrong at your side.
