### ISSUE TITLE
lxqt-panel sometimes hogs the cpu

### ISSUE THREAD

**Issue by mrlemux** [lxde/lxqt#550]
Sometimes, the lxqt-panel hogs 90 Percent of one CPU-Core 
killing the panel often solves the problem

Used applets are the battery watcher, the CPU applet and the time applet

**Comment by mrlemux** [comment]
This seems to be caused by external Applets like the blueman-applet or the network-manager-applet

**Comment by paulolieuthier** [comment]
@mrlemux how have you installed LXQt? Tarballs, git? If you can get latest version from git, could you please test it again?

**Comment by mrlemux** [comment]
I'm using the official packages from Arch Linux, which is the latest 'stable' release.
(I will try the git code asap)

**Comment by vicencb** [comment]
Hello there,
I've been observing the same problem for some time now.

After various tests I've narrowed the issue to the "Sensors" panel widget, specifically to the "Warning about high temperature" checkbox.

The reproducibility of the problem seems to be random on startup, but once reproduced, the cpu usage is deterministically tied to the aforementioned checkbox.

In case the problem depends on the configuration of the widget, here it is:
[sensors2]
alignment=Right
chips\acpitz-virtual-0\temp1\color=#628cb2
chips\acpitz-virtual-0\temp1\enabled=false
chips\acpitz-virtual-0\temp2\color=#628cb2
chips\acpitz-virtual-0\temp2\enabled=false
chips\coretemp-isa-0000\Core%200\color=#628cb2
chips\coretemp-isa-0000\Core%200\enabled=false
chips\coretemp-isa-0000\Core%201\color=#628cb2
chips\coretemp-isa-0000\Core%201\enabled=false
chips\coretemp-isa-0000\Core%202\color=#628cb2
chips\coretemp-isa-0000\Core%202\enabled=false
chips\coretemp-isa-0000\Core%203\color=#628cb2
chips\coretemp-isa-0000\Core%203\enabled=false
chips\coretemp-isa-0000\Physical%20id%200\color=#628cb2
chips\coretemp-isa-0000\Physical%20id%200\enabled=true
tempBarWidth=8
type=sensors
updateInterval=1
useFahrenheitScale=false
warningAboutHighTemperature=true

Hope this helps fixing it.
Regards,
  vicencb.

**Comment by DistantThunder** [comment]
Can confirm this issue on Arch Linux too. Disabling the warning about High temperature allows lxqt-panel process to go back to sane CPU usage.
