### ISSUE TITLE
Panel completely hidden with auto-hide

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#560]
When using the auto-hide the panel is completely hidden. It's not obvious that the panel is running.
In the reserved are a little bit of the panel must be displayed to indicate panel's presence.

**Comment by Esclapion** [comment]
A good thing, no ? If the user hides the panel, it's not to have a bit of it...

**Comment by palinek** [comment]
Actualy the panel is 4px wide when hidden. Should we change that (or make it configurable somehow)?

**Comment by luis-pereira** [comment]
@palinek Precisely. IMO we should use that 4 pixels to hint the user that the panel is there hidde. I think KDE and other panels do it.

**Comment by palinek** [comment]
@luis-pereira curious...i remember, it was done so... but now i see that the panel is invisible (must been happen while i was fiddling with the bad layout after unhiding)..

**Comment by palinek** [comment]
Just tested ... I see a black 4px wide bar on screen edge when the panel is hiden.

**Comment by palinek** [comment]
arrgh... I couldn't find out why following  style is not applied:
```css
LxQtPanel {
    background: white;
}
```
By this, the panel should be white while hiden (because margins are set so `BackgroundWidget` is not visible). But I wasn't able to succeed with that. 
...finaly I've noticed that there is `Qt::WA_TranslucentBackground` attribute set for the `LxQtPanel`). When removed:
```diff
--- a/panel/lxqtpanel.cpp
+++ b/panel/lxqtpanel.cpp
@@ -142,7 +142,6 @@ LxQtPanel::LxQtPanel(const QString &configGroup, QWidget *parent) :
     setWindowFlags(flags);
     setAttribute(Qt::WA_X11NetWmWindowTypeDock);
     setAttribute(Qt::WA_AlwaysShowToolTips);
-    setAttribute(Qt::WA_TranslucentBackground);
     setAttribute(Qt::WA_AcceptDrops);
 
     setWindowTitle("LxQt Panel");
```
the style is applied correctly. But I'm not sure why this attribute is set and if we can broke something removing it.

@paulolieuthier, @PCMan, @intialonso, @jleclanche do you know the reason for usage of `WA_TranslucentBackground` attribute?

**Comment by paulolieuthier** [comment]
@palinek the BackgroundWidget is responsible for showing the desired background. If one wants the panel to be transparent, he can set the a opacity to the panel, and that is applied to BackgroundWidget. That, to work, needs the panel itself to be transparent.

**Comment by palinek** [comment]
With lxde/lxqt-panel@bd37fdf everything said here should be fixed -> hidden panel has color of theme or defined by user (and the transparency also working).
