### ISSUE TITLE
OnlyShowIn/NotShowIn ignored by LXQt

### ISSUE THREAD

**Issue by ariszlo** [lxde/lxqt#582]
I am using LXQt in Ubuntu 14.04 from the lubuntu-dev/lubuntu-daily PPA.

LXQt ignores the OnlyShowIn/NotShowIn keys in *.desktop files and thus some applications that should be hidden in LXQt's Applications menu are not hidden.

Consequently, there are two "Synaptic Package Manager" entries in LXQt's Applications menu, one from synaptic.desktop and one from synaptic-kde.desktop. The result is not just a messy menu. The synaptic-pkexec command of synaptic.desktop properly asks for the admin password and then launches Synaptic. However, synaptic-kde.desktop simply tries to launch Synaptic without asking for the admin password and fails.

synaptic-kde.desktop has this key for a reason: OnlyShowIn=KDE;
KDE reads this key, too, and prompts the user for the admin password: X-KDE-SubstituteUID=true

If LXQt respected the OnlyShowIn=KDE then synaptic-kde.desktop would be hidden from LXQt's Applications menu, and one would not have to guess which "Synaptic Package Manager" entry one should click on.

**Comment by palinek** [comment]
Actually working with these keys were fixed recently in liblxqt...
@ariszlo you are probably talking about panel's "Application menu", right?
@luis-pereira this problem is probably connected to menu-cache. @PCMan are the OnlyShowIn/NotShowIn keys handled in menu-cache?

**Comment by luis-pereira** [comment]
@palinek Initially I thought it was libqtxdg's related. It isn't. I do agree with you, it's probably menucache.

**Comment by luis-pereira** [comment]
@palinek @PCMan It's most certainly this: https://github.com/lxde/libfm/blob/master/src/actions/condition.vala#L510

**Comment by ariszlo** [comment]
Yes, it is, thank you. Meanwhile, I sent this patch to the packagers of the lubuntu-daily ppa:

--- lxqt-common-0.9.1/menu/lxqt-applications.menu.orig	2015-02-14 14:42:58.000000000 +0100
+++ lxqt-common-0.9.1/menu/lxqt-applications.menu	2015-04-15 19:08:42.498733000 +0200
@@ -184,6 +184,7 @@
 		<Exclude>
 			<Or>
 				<Filename>lxqt-config.desktop</Filename>
+				<Filename>synaptic-kde.desktop</Filename>
 			</Or>
 		</Exclude>
 		<Layout>

**Comment by paulolieuthier** [comment]
What are the advantages of menu-cache over libqtxdg?

**Comment by luis-pereira** [comment]
@paulolieuthier It's the cache I suppose. I don't know if there are performance "studies".

**Comment by pmattern** [comment]
As of lxde/lxqt-panel@fd9dd987fe80 I cannot confirm palinek's findings regarding WITHOUT_MENU_CACHE.
Setting cmake option `-DWITHOUT_MENU_CACHE=Yes` lxqt-panel compiles flawlessly but still `NotShowIn=LXQt;` doesn't have any effect. New user profile to avoid artifacts due to old or cached settings.

But there seems to another, possibly related problem:

In desktop entry files files `/usr/share/applications/*.desktop` both `NoDisplay=true` and `Hidden=true` prevent the corresponding topic from appearing in panel's main menu. In `~/.local/share/applications/*.desktop` setting `NoDisplay=true` behaves the same but `Hidden=true` doesn't have any effect.
Whatever the exact behaviour of those two settings is meant to be, the underlying [specification](http://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) doesn't give any hint as to why the behaviour should be different at the said two paths.

FWIW the implementations in other desktop environment aren't exactly consistent either.
KDE behaves the same as LXQt, in Xfce `Hidden=true` is considered in `~/.local/share/applications` as well and LXDE doesn't seem to consider `~/.local/share/applications` at all.

**Comment by Vladimir-csp** [comment]
Similar findings in #876. Possibly XDG handling in Qt has issues.

**Comment by pmattern** [comment]
@Vladimir-csp
Err, the part regarding `Hidden` / `NoDisplay` in #876 isn't similar but the very same finding stated above. I just sort of copied into this issue to have it at a more suitable location.

**Comment by tpgxyz** [comment]
Hi, looks like issue can be noticed with autostart files.
For example lxqt starts all /etc/xdg/autostart/*.desktop not matter if OnlyShowIn=KDE;
NotShowIn=LXQt;

Second i've noticed that autostart files with OnlyShowIn=LXQt; are executed only when in startlxqt script
XDG_CURRENT_DESKTOP is set to "X-LXQt" instead of "LXQt"

https://github.com/lxde/lxqt-common/blob/master/startlxqt.in#L65

**Comment by pmattern** [comment]
@tpgxyz 
Running recent VCS checkouts on Arch Linux x86_64 and i686 I cannot confirm your findings, both of them checked with desktop entry files in directories `$XDG_CONFIG{DIRS,HOME}/autostart`.

The apparent disregard of keys `{Not,Only}ShowIn` in `XDG_CONFIG_DIRS/autostart/*.desktop` could be due to running an outdated version of some LXQt component like lxqt-session or libqtxdg.

That aside both findings could be due to faulty handling of values `[X-]LXQt` in keys `{Not,Only}ShowIn` downstream. Similar issues aren't exactly uncommon right now. E. g. in Fedora 23 `Categories=X-LXQt;[...]` is set in desktop entry files `/usr/share/applications/*.desktop` of many configuration dialogues `lxqt-config-*` but not in menu file `/etc/xdg/menu/lxqt-applications.menu` making all these tools misplaced in the menu.
Unfortunately the whole situation regarding that XDG stuff is quite a mess. I recently tried to sum things up in [this comment](https://github.com/lxde/lxqt-notificationd/pull/44#issuecomment-155380451). You may want to have a look.

**Comment by paulolieuthier** [comment]
Weird thing: I see both "System Settings" and "KDE System Settings" (only the latter must be visible) in the panel's menu, but only "KDE System Settings" in lxqt-runner (searching for "settings"). The thing is that lxqt-runner is also compiled with libmenu-cache by default, and I see nothing special in the code.

**Comment by stefonarch** [comment]
Same here, has always been. OnlyShowIn=XYZ; gets  never applied in menu.

**Comment by luis-pereira** [comment]
Menus generated by libqtxdg
![screen-2016-05-23-21-45-33](https://cloud.githubusercontent.com/assets/62877/15484443/ecc6b6ce-2131-11e6-8bec-22b0ad0d47f6.png)

Menus generated by menu-cache
![screen-2016-05-23-21-53-14](https://cloud.githubusercontent.com/assets/62877/15484464/0a132b5e-2132-11e6-8510-0608fa72b632.png)

**Comment by LStranger** [comment]
This issue looks like for me as a misusing of menu-cache. The libmenu-cache
does not validate desktop environment itself, that is done by design, and
all validation must be done by application using two simple APIs:

 menu_cache_app_get_show_flags()
 menu_cache_app_get_is_visible()

So I think those APIs are never called but full applications list is always
shown. There are detailed docs for those APIs, read them, please.

**Comment by LStranger** [comment]
The menu_cache_app_get_show_flags() may be not much useful but don't miss
another API, please - menu_cache_get_desktop_env_flag() - returned value
should be used by menu_cache_app_get_is_visible() to decide if application
should be shown in menu.
