### ISSUE TITLE
QTerminal doesn't work over VNC

### ISSUE THREAD

**Issue by peyoot** [lxde/lxqt#584]
I can use Qterminal in local login. 
But with vnc4server runing adn login via VNC remotely. I can't input anything in QTerminal!
I use Ubuntu 14.04 with lxqt 0.9

**Comment by palinek** [comment]
Is this a problem of lxqt? @peyoot does it work with other DE?

**Comment by pmattern** [comment]
QTerminal is working flawlessly in an LXQt session provided by TigerVNC (binary vncserver) here. So the problem doesn't seem to affect VNC in general.

To my knowledge both vnc4server and vnc4client provided by Ubuntu are the open source flavor of RealVNC which hasn't been maintained upstream since about nine years, see [Ubuntu changelog](http://changelogs.ubuntu.com/changelogs/pool/universe/v/vnc4/vnc4_4.1.1+xorg4.3.0-37ubuntu5/changelog).
So maybe first try a more recent VNC server? E. g. TightVNC is available in Ubuntu, too. (TigerVNC, imho the best VNC server available right now, is available via third-party repos only in Ubuntu).

On a side note this issue actually doesn't belong to LXQt as QTerminal is developed in a [separate project](https://github.com/qterminal).
