### ISSUE TITLE
Cannot hibernate due to Upower

### ISSUE THREAD

**Issue by flamusdiu** [lxde/lxqt#607]
Looks like Debian remove hibernate function from Upower. So, using systemd, I can't get hibernate to work. I also can't remove Upower due to the hard dependencies (which then would get hibernate to work). What's the trick here?

**Comment by paulolieuthier** [comment]
I proposed to use systemd by default (if it's available) in lxde/liblxqt#40. But ideally, the user would be able to choose it.

**Comment by flamusdiu** [comment]
systemd can use different applications for it if installed instead of itself. Removing UPower fixed hibernate but breaks the Power Panel Widget. =\

**Comment by flamusdiu** [comment]
Looks like the commit does fix my issue. Upower is still required for the widget though. =)

**Comment by paulolieuthier** [comment]
@flamusdiu what power panel widget are you talking about?

**Comment by flamusdiu** [comment]
LXqt Powermanagement

**Comment by paulolieuthier** [comment]
I'm using systemd now (actually, it's the default in git master now) and I can use lxqt-powermanagement without any problem. Please, describe your issues.

**Comment by surlykke** [comment]
2015-04-21 15:46 GMT+02:00 flamusdiu <notifications@github.com>:

> LXqt Powermanagement
>


If UPower is removed then it is as expected that lxqt-powermanagement does
not work. Battery change events and lid closed event comes from UPower
(albeit some of them through solid).

If the issue is that systemd cannot hibernate, then a workaround may by to
configure a custom provider for hibernation. This requires that you have
some command-line command that can do hibernation (perhaps pm-hibernate?
I'm not sure what Debian has). I do not belive we have a gui for setting up
custom providers, and I have not tried setting up such a beast personally,
but I _guess_ it can be done by creating the file ~/.config/lxqt/power.conf
with content something like this:

[General]
__userfile__=true
hibernateCommand=pm-hibernate




br. Chr.

**Comment by paulolieuthier** [comment]
@surlykke systemd is default for power management actions in liblxqt. I don't think it interferes with lxqt-powermanagement.

About systemd not being able to hibernate, we can simply go through all the power providers to see if one of them is able to do it, and then call it.

**Comment by flamusdiu** [comment]
I have to keep looking at this. It looks like it hibernates but doesn't resume from file even though I know that I have that right. =\

**Comment by flamusdiu** [comment]
I will close this while I figure out if it's lxqt or something else causing my current issue.
