### ISSUE TITLE
menu bar misplaced in dualscreen

### ISSUE THREAD

**Issue by hduff** [lxde/lxqt#650]
I initially filed this with Mageia for their Mageia5 release as their bug https://bugs.mageia.org/show_bug.cgi?id=16015. they suggested I file it "upstream" since it appears to be an LXQT bug.

Description of problem:
I have a ViewSonic VP171b (native resolution 1280x1024) attached as an external monitor to my Acer Aspire 5315 laptop (Intel Mobile GM965/GL960 Integrated Graphics Controller). Its native resolution is 1280 x 800. 

When using LXQT as the DE, the menu bar is located where it should be for the laptop screen (at 1280x800) and displays about 1/3 of the way up on the 1280x1024 display.

Switching DEs to LXDE (the only other DE I have on this laptop), places the menu bar in the correct place at the bottom of the screen.

Please let me know what additional information I need to provide.

**Comment by paulolieuthier** [comment]
@hduff what exactly do you call a "menu bar"? Can you provide a screenshot?

**Comment by pmattern** [comment]
And may I suggest posting the output of `xrandr` invoked while the problem exists?

**Comment by hduff** [comment]
Screenshot: http://i.imgur.com/Cav6eNR.png

$ xrandr
Screen 0: minimum 8 x 8, current 1280 x 1024, maximum 32767 x 32767
LVDS1 connected 1280x800+0+0 (normal left inverted right x axis y axis) 331mm x 207mm
   1280x1024     59.91*+
   1280x800      59.91 +
   1024x768      60.00  
   800x600       60.32    56.25  
   768x576       79.37  
   640x480       59.94  

TV1 unknown connection (normal left inverted right x axis y axis)
   848x480       59.94 +
   640x480       59.94 +
   1024x768      59.94  
   800x600       59.94  
VGA1 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      85.00    75.08    70.07    60.00  
   832x624       74.55  
   800x600       85.06    72.19    75.00    60.32    56.25  
   640x480       85.01    75.00    72.81    66.67    60.00  
   720x400       70.08  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

**Comment by hduff** [comment]
On a suggestion from a Mageia QC person, I explored lxqt-config-monitor and found a setting that fixed my problem. I elected to disable the laptop display.

**Comment by pmattern** [comment]
That xrandr output seems a bit odd to me.
I for one have never seen an output "Virtual*" running xrandr on physical devices but only on virtual machines. On all systems I've seen so far the numbering started by zero and a hyphen could be found between type and number off an output, e. g. 'VGA-0' instead of 'VGA1'.
Aside from this the screen is set up faulty. You may try running `xrandr --output LVDS1 --mode 1280x800 --primary --output VGA1 --mode 1280x1024 --right-of LVDS1` where you may also state '--left-of' instead of '--right-of' and see what happens.
If this solves your problem, there'd still be the question why your screen is by default set up that faulty. Does a file ~/.config/autostart/lxqt-config-monitor-autostart.desktop exist? If yes, please post it here as well.

**Comment by hduff** [comment]
My earlier comment may have been misleading. Disabling the laptop display made the panel align at the bottom of the 1280x1024 display instead of 1280x800 display. "Show the same screen on laptop LCD and external monitor" places the panel at the 1280x800 location on the 1280x1024 monitor.

The better choice for me to achieve what I want is likely Configure Panel => Alignment & position => Position: Bottom of desktop 2.

If the default choice is to locate the Panel at the bottom edge of the display, it should do that for all different dimensioned displays attached to the system. My guess is that LXQT makes the decision based only on the dimensions of the primary display. Thank you for providing the ability to make different choices for different-dimensioned displays.

Here is my ~/.config/autostart/lxqt-config-monitor-autostart.desktop with both displays active.
[Desktop Entry]
Type=Application
Name=LXQt-config-monitor autostart
Comment=Autostart monitor settings for LXQt-config-monitor
Exec=xrandr --output LVDS1 --mode 1280x1024 --pos 0x0 --brightness 1 --gamma 1:1:1 --set Backlight 1 --output VGA1 --mode 1280x1024 --rate 75.02 --pos 0x0 --brightness 1 --gamma 1:1:1
OnlyShowIn=LXQt

And with only the external display active.
[Desktop Entry]
Type=Application
Name=LXQt-config-monitor autostart
Comment=Autostart monitor settings for LXQt-config-monitor
Exec=xrandr --output LVDS1 --off --output VGA1 --mode 1280x1024 --rate 75.02 --pos 0x0 --brightness 1 --gamma 1:1:1
OnlyShowIn=LXQt

Before selection of the  "Bottom of desktop 2" setting, switching between the laptop display being off and on would make the Panel re-locate to the 1280x800 position on both displays upon logging back in. Using the "Bottom of desktop 2" appears to have solved that annoyance. It does, however, make the Panel disappear from the laptop display.

I have to say as a longtime user of LXDE, I really like what you folks have done with LXQT and it will become my default DE..

**Comment by pmattern** [comment]
First a note regarding dialog window "Configure panel" as opened from panel's context menu.
Under Panel (left pane) - Alignment & Position (right pane) - Position the term *desktop* in "{Top,Left,...} of *desktop*" is actually wrong. Rather, this should be "... of monitor", much as in its LXDE counterpart, or maybe, depending on the configuration, "... of screen".
(This was discussed already on the issue tracker but to my regret I couldn't find it right now.)

To further track the actual problem please perform the following steps. Confirm all xrandr settings by running simply `xrandr` after each command `xrandr --output foo ...`.

1. If you should still be using that epic xorg.conf posted on bugs.mageia.org just move it out of the way. It's a possible source of artifacts and what ever it's meant to achieve won't be needed to track this issue. Restart the X window system.
2. Launch an LXQt session.
3. Place the monitors adjacent by running `xrandr --output LVDS1 --mode 1280x800 --primary --output VGA1 --mode 1280x1024 --right-of LVDS1`. Tweak settings "{Bottom,Top,...} of desktop {1,2}" as described in first paragraph of this comment. The panel should always be placed on one of the monitors only and at the expected position.
4. Configure the monitors to display the same content in a reasonable way by running `xrandr --output LVDS1 --mode 1280x1024 --pos 0x0 --output VGA1 --mode 1280x1024 --pos 0x0`. Tweak settings "{Bottom,Top,...} of desktop {1,2}" as described in first paragraph of this comment. The panel should always be displayed on both monitors at the chosen position.
5. Configure the monitors to display the same content in an insane way by running `xrandr --output LVDS1 --mode 1280x800 --pos 0x0 --output VGA1 --mode 1280x1024 --pos 0x0`. Toggle n in "Bottom of desktop *n*" as described in first paragraph. The panel will now be displayed either on the bottom of your external monitor only or both at the bottom of your laptop panel and the faulty position on your external monitor.
6. Launch an LXDE session and repeat steps 3.-5. The findings will be the very same.

**Comment by hduff** [comment]
In #5, it would not allow a 1280x1024 configuration for the 1280x800 display, saying it was not available.

Otherwise, following your instructions, everything worked correctly.

Thank you.

**Comment by pmattern** [comment]
The "1280x800" display is meant to be run at this very resolution and not at 1280x1024 in step 5: `xrandr --output LVDS1 --mode *1280x800* [...]`!?

Step 5 is actually the crucial one...

**Comment by pmattern** [comment]
Attempts to reproduce the problem strongly suggest the following:
The strange placement of panels happens when two monitors are configured to display the same content at different resolution like this
![lxqt_placement-panel-vs-randr_issue-lxqt-650](https://cloud.githubusercontent.com/assets/9860801/7909476/c28d7c16-084c-11e5-8e70-55a207d6eb1f.png)
reflecting the first xrandr output posted in this thread. Using this settings a panel gets displayed both at the bottom of LVDS1 and distant from the bottom on VGA1 if it's configured to be displayed at the bottom of LVDS1. If a panel is configured to be displayed at the bottom of VGA1 it will be displayed at the bottom of VGA1 but not at all on LVDS1.
A panel always gets displayed as expected if two monitors are configured to be placed adjacent in a reasonable way or to display the same content at the same resolution.
All those findings are the very same on LXDE, LXQt and KDE Plasma 5 using the corresponding panels.

The reason why the OP ran into this problem on LXQt only is that a setting as depicted in the drawing was used on LXQt only. This in turn is probably due to some misbehaviour of lxqt-config-monitor:
If changes are applied but "No" is hit in the dialogue to confirm, lxqt-config-monitor doesn't revert to the setting that had been valid before but sets all outputs to their recommended resolution at position +0+0.

Aside from this it could be questioned whether panels should be expected to behave reasonably if monitors are configured to display the same content at different resolutions.
To my knowledge RandR doesn't allow for zooming the content of one monitor to another one of a larger resolution. Thus any attempt to display the same content at different resolutions will yield crappy results. In particular, if the ratio of the two devices is different.
So I definitely think nothing has to be changed at the panel's side. Trying to display the same content at different resolutions just doesn't make sense right now.

**Comment by pmattern** [comment]
Underlying problem is now discussed in #680.
