### ISSUE TITLE
'Leave' disappeared from menu bar

### ISSUE THREAD

**Issue by hterh** [lxde/lxqt#653]
After recent update there is no longer a menu item for leave (restart/log out/shut down). 
![screenshot - 26-05-15 - 09 00 04-cropped](https://cloud.githubusercontent.com/assets/9549846/7807645/805bdd06-038d-11e5-87e6-1620228994ae.png)

This on a Xubuntu 14.04 (Chalet OS) installation. In Xfce and LXDE desktops nothing has changed.

**Comment by pmattern** [comment]
According to the screenshot your Application menu is relying on a *.menu file other than LXQt's genuine lxqt-applications.menu provided by lxqt-common.

Please open dialog window "Main Menu settings" from Application menu's context menu - "Configure Application menu" and look for the path at "Menu file".
If something else than lxqt-applications.menu is used replace it by the latter to see whether the problem gets fixed that way (following commands assumed to be run as root, either from a regular root shell session or by prefixing 'sudo '):
* update your package cache: `apt-get update`
* look for package lxqt-common: `dpkg --list lxqt-common` (see status in first column)
* install component lxqt-common if needed: `apt-get install <package name as provided by dpkg --list>`
* make Application menu use lxqt-applications.menu from the dialog window mentioned above. Use button "..." to chose the file to avoid using a path that doesn't apply to your system (it could differ from the usual /etc/xdg/menu due to changes made by your distro). You may have to start a new session (log out / in again) for this to take effect.

Also, you may want to check which package is providing an eventual *.menu other than lxqt-applications.menu by running `dpkg --search <path to *.menu that's used>`.

**Comment by hterh** [comment]
lxqt-applications.menu is shown in Main Menu settings.
The output of dpkg --search *.menu is here below. 
I checked again, but also lxde mode fails to log out (though the menu entry is there). 
I plan to dump this installation and on this partition install regular Xubuntu (15.04) with LXQt from ubuntu repository and report when ready.

henk@henk-Veriton-M261:~$ dpkg --search *.menu
software-center: /usr/share/app-install/menu.d/extra-unity-categories.menu
gnome-menus: /etc/xdg/menus/gnome-applications.menu
app-install-data: /usr/share/app-install/desktop/applications.menu
google-chrome-stable: /usr/share/menu/google-chrome.menu
software-center: /usr/share/app-install/desktop/software-center.menu
playonlinux: /usr/share/playonlinux/etc/playonlinux-Programmes.menu
software-center: /usr/share/app-install/menu.d/featured.menu
wine1.6: /etc/xdg/menus/applications-merged/wine.menu
gnome-menus: /etc/xdg/menus/gnome-flashback-applications.menu
menu-xdg: /etc/xdg/menus/debian-menu.menu
kdelibs5-data: /etc/xdg/menus/kde4-applications.menu
lxmenu-data: /etc/xdg/menus/lxde-applications.menu
software-center: /usr/share/app-install/menu.d/top-rated.menu
lxqt-config: /etc/xdg/menus/lxqt-config.menu
xubuntu-default-settings: /etc/xdg/xdg-xubuntu/menus/xfce-applications.menu
xubuntu-default-settings: /etc/xdg/xdg-xubuntu/menus/xfce-settings-manager.menu
xfce4-settings: /etc/xdg/menus/xfce-settings-manager.menu
lxqt-common: /etc/xdg/menus/lxqt-applications.menu
kde-runtime-data: /etc/xdg/menus/kde-information.menu
libgarcon-common: /etc/xdg/menus/xfce-applications.menu
software-center: /usr/share/app-install/menu.d/whats_new.menu

**Comment by pmattern** [comment]
Hm. So you really saw something like this
![lxqt_panel_applications-menu_vs-leave- 653](https://cloud.githubusercontent.com/assets/9860801/7811166/786e93d4-03a8-11e5-9955-3112d4f1cd1e.png)
too? Just to avoid misunderstandings as this is really too weird: lxqt-applications.menu definitely doesn't comprise items "Chrome Apps" or "Wine" in its top level.

**Comment by hterh** [comment]
Yes, this is how to looks like. I have seen also on Lubuntu as well as Debian 8 with XFCE that an entry for Chrome apps is introduced in the menu bar when Google Chrome is installed. I have no experience with Whine which was brought in by Chalet OS.

**Comment by hterh** [comment]
Have now installed Xubuntu 15.04 with updates and LXQt 0.9 from ubuntu repository. A screen dump shows again Leave (but also Lock Screen) have disappeared from the menu. I can only exit from ctrl-alt-F2 -> ctrl-alt-del. I never experienced this before with LXQt. (I use Xubuntu because  LXQt cannot yet be installed on Lubuntu (..!) from ubuntu repository.)
![screenshot_2015-05-26_16-24-38-cropped](https://cloud.githubusercontent.com/assets/9549846/7814994/f7662a72-03c5-11e5-8d98-66ab0d599ece.png)

**Comment by hterh** [comment]
And Chrome apps appeared again as entry in the menu bar after installing Chrome.

**Comment by pmattern** [comment]
Which repository are you using to get LXQt on Xubuntu?

**Comment by hterh** [comment]
question 1: ppa:lubuntu-dev/lubuntu-daily

question 2: 
 lxqt
liblxqt-data                                    install
liblxqt0                                        install
lxqt-about                                      install
lxqt-admin                                      install
lxqt-common                                     install
lxqt-config                                     install
lxqt-globalkeys                                 install
lxqt-metapackage                                install
lxqt-notificationd                              install
lxqt-openssh-askpass                            install
lxqt-panel                                      install
lxqt-policykit                                  install
lxqt-powermanagement                            install
lxqt-qtplugin                                   install
lxqt-runner                                     install
lxqt-session                                    install

**Comment by pmattern** [comment]
Item "Leave" is comprising all desktop entry files (*.desktop) featuring category X-Leave, see extract from lxqt-applications.menu,
```
                <!-- Leave -->
        <Menu>
                <Name>X-Leave</Name>
                <Directory>lxqt-leave.directory</Directory>
                <Include>
                        <And>
                                <Category>X-Leave</Category>
                        </And>
                </Include>
        </Menu>  <!-- End Leave -->
```
which applies to files lxqt-{hibernate,leave,logout,reboot,shutdown,suspend}.desktop.
```
$ grep -E 'Categories.*X-Leave' /usr/share/applications/*.desktop
/usr/share/applications/lxqt-hibernate.desktop:Categories=LXQt;X-Leave
/usr/share/applications/lxqt-leave.desktop:Categories=LXQt;X-Leave
/usr/share/applications/lxqt-logout.desktop:Categories=LXQt;X-Leave
/usr/share/applications/lxqt-reboot.desktop:Categories=LXQt;X-Leave
/usr/share/applications/lxqt-shutdown.desktop:Categories=LXQt;X-Leave
/usr/share/applications/lxqt-suspend.desktop:Categories=LXQt;X-Leave
```
Item "Lock Screen" is comprising just file lxqt-lockscreen.desktop
```
        <!-- Screensaver -->
        <Menu>
                <Name>Screensaver</Name>
                <Include>
                <Filename>lxqt-lockscreen.desktop</Filename>
                </Include>
        </Menu> <!-- End Screensaver -->
```
All those desktop entry files are relying on binary lxqt-leave
```
$ grep Exec /usr/share/applications/lxqt-{hibernate,leave,logout,reboot,shutdown,suspend,lockscreen}.desktop 
/usr/share/applications/lxqt-hibernate.desktop:Exec=lxqt-leave --hibernate
/usr/share/applications/lxqt-leave.desktop:Exec=lxqt-leave
/usr/share/applications/lxqt-logout.desktop:Exec=lxqt-leave --logout
/usr/share/applications/lxqt-reboot.desktop:Exec=lxqt-leave --reboot
/usr/share/applications/lxqt-shutdown.desktop:Exec=lxqt-leave --shutdown
/usr/share/applications/lxqt-suspend.desktop:Exec=lxqt-leave --suspend
/usr/share/applications/lxqt-lockscreen.desktop:Exec=lxqt-leave --lockscreen
```
Both the desktop entry files and binary lxqt-leave are provided by lxqt-session, see corresponding search on Arch Linux
```
$ pacman -Qo /usr/share/applications/lxqt-{hibernate,leave,logout,reboot,shutdown,suspend,lockscreen}.desktop /usr/bin/lxqt-leave 
/usr/share/applications/lxqt-hibernate.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-leave.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-logout.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-reboot.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-shutdown.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-suspend.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/share/applications/lxqt-lockscreen.desktop is owned by lxqt-session-git 0.9.0.25.g720452e-1
/usr/bin/lxqt-leave is owned by lxqt-session-git 0.9.0.25.g720452e-1
```
none of them exists in recent PPA package lxqt-session
```
$ dpkg --listfiles lxqt-session | grep -E 'lxqt-leave|desktop' 
/usr/share/applications/lxqt-config-session.desktop
```
which is the reason of the problem. So it's a downstream issue that you may want to report as such.

That Alt+Foo+Bar battle isn't needed despite the items are missing in main menu.
You can launch LXQt runner by hitting Alt+F2 which is providing all those actions from its own menu, too. Button to access varying, arrow in following screenshot.
![lxqt_runner_disappear-upon-menu_main-gui](https://cloud.githubusercontent.com/assets/9860801/7824552/232066ee-0404-11e5-896e-d9a87d1e6e40.png)
(The fact that the main UI will disappear after opening the menu is due to a bug that's possibly caused by a Qt issue. Something on my ToDo list...)

Absolutely couldn't reproduce how to get a topic "Google apps" into the menu. But this isn't related to this problem in any way.

**Comment by hterh** [comment]
Here my Chrome Apps that appear in its submenu,
(But strange enough VLC didn't make it to the submenu Sound & Video after installing in Xfce).
![screenshot_2015-05-27_09-22-21crop](https://cloud.githubusercontent.com/assets/9549846/7831045/20b3fba6-0453-11e5-80d6-d654fd85772b.png)

**Comment by pmattern** [comment]
Of course, I forgot. Both {lxqt,xfce}-applications.menu feature \<Default{Apps,Directory,Merge}Dirs/\>, see [Desktop Menu Specification](http://standards.freedesktop.org/menu-spec/latest/ar01s04.html). Chrome Apps seem to make use of that by putting their stuff into $XDG_DATA_HOME/{applications,desktop-directories} and $XDG_CONFIG_HOME/menus (for variables see [Base Directory Specification](http://standards.freedesktop.org/basedir-spec/latest/ar01s03.html)).

> (But strange enough VLC didn't make it to the submenu Sound & Video after installing in Xfce).

In Debian 8 "Jessie" an item "Sound & Video" doesn't exist in Xfce but "Multimedia" only. "Sound & Video" does exist in LXQt, though. So maybe you confused the two here?
This could very well be as in LXQt the Application menu sometimes doesn't get updated correctly. Couldn't figure out the exact conditions so far. But normally this can be fixed by updating the timestamp of lxqt-applications.menu `touch /etc/xdg/menu/lxqt-applications.menu` (root).

Btw. PPA ppa:lubuntu-dev/lubuntu-daily is working flawlessly on Lubuntu 15.04 x86_64 in a KVM/QEMU VM here.

**Comment by erikthered** [comment]
My "Leave" menu has also disappeared since updating from the lubuntu-dev/lubuntu-daily PPA yesterday. I'm running on 15.04, which I did a minimal install and then installed from lxqt from the PPA. The leave menu had been working fine until yesterday's update.

Let me know if you need any further information.

**Comment by erikthered** [comment]
I was able to fix my issue by installing the lxqt-leave package from the ppa.

**Comment by pmattern** [comment]
> I was able to fix my issue by installing the lxqt-leave package from the ppa.

Confirmed.
So package lxqt-leave was apparently split from lxqt-session in that PPA. No clue as to why, in particular as it seems to be the only package where they deviate from upstream.
Also, a pity they don't provide those archives needed by apt-file. Would have allowed to figure this out much more quickly.

**Comment by hterh** [comment]
lxqt-leave worked for me too.
Although I thought I had rebooted earlier on, VLC does now show up in LXQt under "Sound & Video", so this is solved as well.

**Comment by rogerfranz** [comment]
Had the same problem, same solution: add the package lxqt-leave.
I think lxqt-metapackage in the PPA needs to be updated with a dependency (or at least a recommend) of lxqt-leave.

**Comment by paulolieuthier** [comment]
@gilir is that something you can do?

**Comment by pmattern** [comment]
Addendum:
As of 2015-10-10 package `lxqt-leave` "depends" on `lxqt-metapackage`.

**Comment by agaida** [comment]
@gilir - please revert the splitting lxqt-leave if you want to be compatible with the upcoming debian packages - and i would also suggest to use the alioth repos as a base for the ubuntu packages.

**Comment by gilir** [comment]
@agaida well, as far as I know, lxqt-leave work without lxqt-session, and work well as a standalone app, so it makes sense to have it in a separate binary. Also, we had the same problem with lxsession / lxsession-logout. There are both independent, and people asked us to split the package, because they want to replace lxsession or lxsession-logout with something else.

**Comment by agaida** [comment]
it make no sense at all - but do it like you want to - we will not take care in future versions i think.
