### ISSUE TITLE
lxqt-panel: volume plugin: add notifications

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#674]
Please add notifications (via libnotify) to volume plugin when controlled channel volume changes or is switched (even when some other tool changes it).

**Comment by YamashitaRen** [comment]
Good idea.
It shouldn't be limited to volume and apply to brightness too, though.
Is there an alternative tool that we could use in the meantime ?

**Comment by pmattern** [comment]
Hm, but isn't this implemented already? Pressing multimedia keys to adjust the volume definitely triggers notifications by `lxqt-notificationd` here (Arch Linux x86_64, all LXQt components from latest VCS checkouts).

Brightness doesn't belong here but to #36 or one of the issues stated there.

**Comment by YamashitaRen** [comment]
You're right.
Curiously, using kmix in the same time made them disappear...

**Comment by pmattern** [comment]
Interesting. But not sure whether something should be done at LXQt's side to mitigate effects of a tool that's belonging to another desktop environment as long as a counterpart is provided by LXQt and working well which applies to `kmix`. I'd tend to say no...

**Comment by yan12125** [comment]
Volume plugin suddenly fails to show notifications after rebuild all components from git.

Software versions:
```
$ pacman -Q lxqt-panel-git lxqt-notificationd-git 
lxqt-panel-git 0.10.0.128.gb5b6101-1
lxqt-notificationd-git 0.10.0.11.g0a0a1d5-1
```

Another program on Arch [kalu](https://github.com/jjk-jacky/kalu) can show notifications fine, so I guess it's a problem in the volume plugin.

**Comment by pmattern** [comment]
@yan12125 
I cannot confirm your findings running the very same commits of lxqt-panel and lxqt-notificationd on Arch Linux, both on a system running "bare metal" and in a QEMU virtual machine.
Is your underlying Arch Linux system up to date and did you re-compile *all* LXQt components in a suitable order? I'm asking as we've recently had [an other problem](https://github.com/lxde/lxqt/issues/1020) with notifications which ceased after updating both the underlying systems and LXQt before we could figure out what was actually happening.

**Comment by pmattern** [comment]
@Vladimir-csp 
Are you still seeing this problem? I'm asking as I'm under the impression this issue can be closed.

**Comment by yan12125** [comment]
Already have qt5 5.7.0. @pmattern What do you mean by "in a suitable order"? I just built ```lxqt-desktop-git``` from AUR. If there's a non ```-git``` dependent package, I stop the process, build the corresponding ```-git``` package, and then restart the build. Is it correct?

**Comment by stefonarch** [comment]
Actually I did not notice that notification of volume disappeared, but it has here too.

**Comment by pmattern** [comment]
> [...] disappeared, but it has here too.

Strange. As said [above](https://github.com/lxde/lxqt/issues/674#issuecomment-237188817) this is working like a charm here.

Or is there some misunderstanding and you're talking about something other than multimedia keys that you expect to trigger the desktop notifications, e. g. some application?

If you're talking about keys is there any chance you can post the output of `xev`?

@yan12125 
Well, basically this should be the right approach. But in order to install a metapackage like this from the AUR you'll probably use an AUR helper. And in my experience these tend to do unexpected stuff when it comes to complex dependencies.
So IMO the more secure approach is to use a script like e. g. https://gist.github.com/pmattern/8056c4bd7104ae640b79 (which pulls some additional software you can of course ommit).

**Comment by stefonarch** [comment]
On my keyboard (no laptop) I have no multimedia keys, so I use cltr+up/ctrl+down and there was no notification, I just changed them now  to alt+prior/alt+next and notifications are working now as they should. I just wonder why they stopped.

**Comment by yan12125** [comment]
I guess I've found the problem - openbox registers 3 volume-related special keys, namely **XF86AudioLowerVolume**, **XF86AudioRaiseVolume** and **XF86AudioMute**. As a result, lxqt-globalkeysd can't hook these keys, so these keys are never processed by lxqt-panel's volume plugin.

**Comment by pmattern** [comment]
@stefonarch 
All the shortcuts you mention are working here. Could you test what happens when you revert to `Ctrl+{Up,Down}`?

@yan12125 
To my knowledge these keys have never been assigned by any of the Openbox configuration files we've been using as template so far. So did you use a modified version as template or modify the file by some other tool like `obkey`? Also, lxqt-globalkeysd normally throws a warning when it can't assign a particular key as it had already been assigned by the window manager before, see e. g. #1032. Do you see some warning like that?
Does the problem stop for you when you make sure those keys are *not* assigned by Openbox?

**Comment by yan12125** [comment]
Yes, my problem is solved after removing these keys from ```~/.config/openbox/lxqt-rc.xml```. Have no idea why my file contains those lines. I have once installed LXQT in Jul 2014 and maybe I've done something terrible then.

**Comment by stefonarch** [comment]
> All the shortcuts you mention are working here. Could you test what happens when you revert to Ctrl+{Up,Down}?

Reverting to ctrl+up/down notifications are working too now.

**Comment by pmattern** [comment]
Still looks to me like we can close this, tbh. Maybe wait until @Vladimir-csp will have another say.

**Comment by Vladimir-csp** [comment]
I am a bit out of the loop now. Are there currently fresh packages being available for Stretch?
Anyway, if volume plugin shows notification when you tweak volume in i.e. alsamixer, then the issue is closed.

**Comment by pmattern** [comment]
> Anyway, if volume plugin shows notification when you tweak volume in i.e. alsamixer

This doesn't happen here but I don't see how this could be useful either: desktop notifications are meant to inform users about things they would not get aware of otherwise. But if you adjust some volume *in* alsamixer as you write you're already seeing what happens anyway.

Again, this boils down to the question when notifications should be expected to come up.
It's obvious they should when corresponding keys are hit. But other than that?

**Comment by Vladimir-csp** [comment]
it's not specifically about alsamixer. At some point something in background might change the volume, it would be handy if volume plugin, while running, would indicate the change. Think of standalone usage of lxqt-panel.
I'm currently governing volume using amixer via openbox shortcuts, and qasmixer sitting in the tray shows me notifications. This interoperability is quite handy and contributes to modularity of the environment, the only problem is that qasmixer uses own notification instead of libnotify, lxqt-panel could do better.

**Comment by palinek** [comment]
..see lxde/lxqt-panel#406

**Comment by stefonarch** [comment]
Translating I noticed that it says
`Volume: 45
`better would be adding %:
`Volume: 45 %
`
https://github.com/lxde/lxqt-panel/blob/310140f842b8b809b1165106154f93833a269802/plugin-volume/lxqtvolume.cpp#L289 but it needs an update on all *.ts files too.

**Comment by palinek** [comment]
> better would be adding %:

Added in dc915160.

@m4sk1n please, update the lxqt-l10n
