### ISSUE TITLE
Adjustable opacity for each window?

### ISSUE THREAD

**Issue by alexrichert** [lxde/lxqt#675]
Until recently, in XFCE it was possible to Alt+[vertical mouse scroll] over the title of a window to adjust its opacity (which is occasionally handy for, say, typing into the window while you read from another window beneath it). Would this be possible to implement in LXQt? I'm not entirely sure what the relationship between LXQt and Openbox is and which one is responsible for dealing with something like that, so I apologize in advance if this is a stupid question. But it would be a cool feature! And it would certainly ease my inevitable transition over to LXQt!

**Comment by pmattern** [comment]
Regarding the X window system transparency is handled by a compositor which may be part of the window manager itself, e. g. KWin or Xfwm, or provided as external component, e. g. Compton supplementing Openbox.
Keyboard shortcuts affecting windows as a whole are handled by window managers. As for mouse scrolling I have to admit I don't know how it's handled in general. But regarding Xfce it seems to be handled by Xfwm, too, see dialog "Window Manager Tweaks", Tab "Accessibility".
So all in all there's nothing we can do about it in LXQt as it's an upstream issue.

Note you can use Xfwm and in fact a couple of other window managers on LXQt as well, Openbox is just the window manager the most frequently used but not mandatory. (The latter is even likely to change as it doesn't look like Openbox will ever support Wayland.)
For now you'll even have configuration binaries xfwm4-settings ("Window Manager"), xfwm4-tweaks-settings ("Window Manager Tweaks") and xfwm4-workspace-setting ("Workspaces") available in LXQt's main menu - albeit only due to a [bug](https://github.com/lxde/lxqt/issues/582). If that bug gets fixed you can still keep them in your menu e. g. by copying the corresponding desktop entry files to $XDG_DATA_HOME/applications and modify key OnlyShowIn.

Regarding that special feature transparency by Alt+scrolling it doesn't seem to work any longer since that "shortcut" was assigned a zoom feature in Xfwm 4.11.1, see [announcement](https://mail.xfce.org/pipermail/xfce-announce/2013-December/000295.html).
Yet you may get it back should this behaviour of Xfwm get changed again using it as stated above. Also, chances are that other window managers do provide something like this which I don't know.
