### ISSUE TITLE
Update link to Mageia, on the website

### ISSUE THREAD

**Issue by stormi** [lxde/lxqt#734]
Now that Mageia 5 has been released, the proper link for lxqt would be:

http://mageia.madb.org/package/show/application/0/name/task-lxqt

This link will always point at task-lxqt package of the latest stable version of Mageia (currently Mageia 5). I can promise that, since I'm the author of madb.org

**Comment by pmattern** [comment]
The link you stated was added both to [GitHub wiki's startpage](https://github.com/lxde/lxqt/wiki) and [lxqt.org](http://lxqt.org). The former will eventually be abandoned so as to maintain the list at a single location only but that's a different story.

If it's okay like this you may close this issue, otherwise let us know what's wrong.

**Comment by stormi** [comment]
It's good for me, thanks!
