### ISSUE TITLE
Please, add tooltip text to the System Statistics panel plugin!

### ISSUE THREAD

**Issue by eugen-br** [lxde/lxqt#741]
Hello!
It would be great to have a tooltip text to see some numbers and not only a graph of eg. CPU usage on the System Statistics panel plugin.
Thanks!
Eugen

**Comment by pmattern** [comment]
Should be introduced, indeed. In particular to be consistent with lots of (all?) other plugins providing information of a similar kind, e. g. cpuload, volume or clock.

**Comment by palinek** [comment]
@eugen-br, @pmattern something like in the lxde/lxqt-panel#229 ?

**Comment by pmattern** [comment]
Regarding the text within the tooltips introduced by this PR some details *could* be improved, IMHO.
The tooltips sometimes refer to 'Type' as stated in 'Data' in the plugin's configuration dialog and sometimes to 'Source' at the same location. Namely CPU → always "CPU", Memory → value of 'Source' (initial letter capitalized unlike in configuration window), Network → always "Net". I think this should be consistent. Maybe it would even be good to state both Type and Source in the tooltips, e. g. something like `Network (eth0)`.
Translations like e. g. "Prozessor" as German translation of CPU can be seen in the plugin's configuration dialog but not within the tooltips.

On an off-topic side note I wonder whether it's intentional that there's always a string "cpu" *plus* strings "cpu[0,1,2...]" in Data - Type CPU - Source.

**Comment by palinek** [comment]
> Maybe it would even be good to state both Type and Source in the tooltips' headers, e. g. something like Network (eth0).

done in lxde/lxqt-panel@695fb945632f69d698c0d9561a9c18f22f239cc4

> Translations like e. g. "Prozessor" as German translation of CPU can be seen in the plugin's configuration dialog but not within the tooltips.

> On an off-topic side note I wonder whether it's intentional that there's always a string "cpu" plus strings "cpu[0,1,2...]" in Data - Type CPU - Source.

Translation done in lxde/lxqt-panel@d133498394959532438e3189562740688b2f2628 ... however the `source` is tightly coupled with strings provided by `libsysstat` ... so I made a workaround for translation (enumerating all known strings in the source to make it translatable)

**Comment by pmattern** [comment]
> > Maybe it would even be good to state both Type and Source in the tooltips' headers, e. g. something like Network (eth0).

> done in lxde/lxqt-panel@695fb945632f69d698c0d9561a9c18f22f239cc4
> Translation done in lxde/lxqt-panel@d133498 ... how

Both really pretty good, IMHO.
Would look even a bit better if there was a blank space between \<type\> and (\<source\>).

> On an off-topic side note I wonder whether it's intentional that there's always a string "cpu" plus strings "cpu[0,1,2...]" in Data - Type CPU - Source.

Persists. Just saying.
