### ISSUE TITLE
lxqt-panel no access to menu / causes 100% cpu load on one core 

### ISSUE THREAD

**Issue by renegat** [lxde/lxqt#759]
This is a sporadic issue! It happens on about every third or fourth login:

Package:  lxqt-panel 0.9.0-2
Architecture: x86_64 GNU/Linux 4.1.2-2-ARCH
Device: Intel NUC DN2820FYKH

What it isn't doing:
After login the menu button at the left of the panel does not open the menu. It does nothing!
One core is running at 100% load caused by lxqt-panel.

Steps to reproduce:
Restart lxqt several times till it happens.
Only way to log out then is to pass 'kill -9 -1'
When the issue appears you have to restart lxqt until panel works normal again.

**Comment by pmattern** [comment]
A pretty similar issue was reported and fixed in #686.
You seem to run Arch Linux. Any chance you can verify using the Git packages from AUR? Once you're a bit familiar with AUR it's actually pretty easy.
Note that you have to use *all* LXQt components from their Git checkout as heavy changes took place under the hood recently and it's pretty likely you'll see artifacts if you exchange just a fraction of components.

**Comment by renegat** [comment]
Also it was quite a pita due to missing dependencies in the PKGBUILDS like qt5-svg, libdbusmenu-qt5 and libsysstat-git and some git-packages pulling non git-packages as dependencies which you then have to delete and replace again - I made it and installed a pure lxqt-git on a quite similar system with Intel Celeron J1800 / ARCH Linux x86_64. Runs quite smooth!
Good news: The issue described above does not seem to appear with the lxqt-git packages.
Also it is nice to see that there is still actual development and improvement on lxqt after I have not heard anything about it these days since the 0.9 release.
Keep up the good work!
I'am looking forward for lxqt 1.0

**Comment by pmattern** [comment]
The maintenance of the AUR packages on Arch Linux could all in all be better, yes. Note that some problems are solved in the new AUR4 only right now, though.
yaourt you can [be pointed to it](https://wiki.archlinux.org/index.php/Yaourt#Yaourt_not_using_new_AUR4) by a line `AURURL="https://aur4.archlinux.org"` in /etc/yaourtrc or ~/.yaourtrc. Other AUR helpers may feature something similar which I didn't test myself yet.
You may mitigate the installation woes by using a script like https://gist.github.com/pmattern/8056c4bd7104ae640b79. Comprises some components in addition to LXQt so you may want to drop or add some packages or use an AUR helper other than yaourt. Only working with AUR 4 right now due to the reasons stated above.
