### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#764]
Hi,

there is no sound with LXQt on my computer though KDE on the same machine outputs sound.

OS: Kubuntu 15.04 (64 bit)
ALSA version: k3.19.0-24-generic
Chipset: 00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)

~> lsmod | grep snd
> snd_hrtimer            16384  1 
> snd_hda_codec_hdmi     53248  1 
> snd_hda_codec_realtek    86016  1 
> snd_hda_codec_generic    69632  1 snd_hda_codec_realtek
> snd_hda_intel          36864  4 
> snd_hda_controller     32768  1 snd_hda_intel
> snd_hda_codec         143360  5 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_intel,snd_hda_controller
> snd_hwdep              20480  1 snd_hda_codec
> snd_pcm               106496  4 snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_controller
> snd_seq_midi           16384  0 
> snd_seq_midi_event     16384  1 snd_seq_midi
> snd_rawmidi            32768  1 snd_seq_midi
> snd_seq                69632  3 snd_seq_midi_event,snd_seq_midi
> snd_seq_device         16384  3 snd_seq,snd_rawmidi,snd_seq_midi
> snd_timer              32768  3 snd_hrtimer,snd_pcm,snd_seq
> snd                    90112  20 snd_hda_codec_realtek,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_seq_device
> soundcore              16384  2 snd,snd_hda_codec

Regards,
Ettore

**Comment by pmattern** [comment]
Please let us know how LXQt was installed.

Also, you may want to have a look at #612, in particular whether your findings can be related to what's explained in [this comment](https://github.com/lxde/lxqt/issues/612#issuecomment-118814394) which can be verified by running `alsamixer` in a terminal emulator.

That issue also covers another problem affecting PPA ppa:lubuntu-dev/lubuntu-daily only, namely the lack of topic "PulseAudio" in the configuration dialog of LXQt's panel plugin to adjust the volume (plugin-volume). This problem still exists which doesn't make tracing the problem any easier...

**Comment by Atalanttore** [comment]
I've installed LXQt 0.9 from the PPA ppa:lubuntu-dev/lubuntu-daily next to KDE 5.

**Comment by pmattern** [comment]
So you're indeed probably suffering from the problems described in my last post.
That whole stuff may look a bit complicated. Yet I'd encourage you to try and reproduce the findings / proposals in #612 so that we can nail your problem down.

**Comment by Atalanttore** [comment]
The "Volume Control Settings" shows no PulseAudio though it is installed.

![lxqt_lautstarkeeinstellungen](https://cloud.githubusercontent.com/assets/628474/9037112/1930da1e-39e8-11e5-8642-60a89e6194c7.png)

![pavucontrol_in_muon](https://cloud.githubusercontent.com/assets/628474/9037156/a2f9c3b4-39e8-11e5-9b72-a2b86a599af6.png)

**Comment by palinek** [comment]
> The "Volume Control Settings" shows no PulseAudio though it is installed.

AFAIK there's no pulse support compiled-in in lubuntu daily PPA packages... if you need it, you have to report that in downstream, not here

**Comment by gilir** [comment]
FYI, pulseaudio support was added yesterday to lxqt-panel in Lubuntu PPA. Sorry for the delay.

**Comment by Atalanttore** [comment]
Especially for me …… many thanks :)

**Comment by Atalanttore** [comment]
I forgot to write that sound works properly with PulseAudio.

**Comment by baptx** [comment]
I also have a sound problem with PulseAudio and LXQt since several months after switching from Xfce desktop environment.
If I select "Alsa" in the volume control settings, it works great (except for Firefox which requires PulseAudio or using a tool like apulse).
If I select "PulseAudio" in the volume control settings, I can see the status "Dummy Output" and the sound will not work, even if I use `pulseaudio --kill` and `pulseaudio --start` commands.
I found a workaround by disabling the sound card on startup, I I add `blacklist snd_hda_intel` at the end of the file `/etc/modprobe.d/blacklist.conf` and enable the sound card with the command `sudo modprobe snd_hda_intel` after LXQt session has started, the sound will work with PulseAudio (I can now see the status "Built-in Audio Analog Stereo" instead of "Dummy Output").
I am using version 0.13.0 of LXQt.
Do you have an idea where the problem comes from? Should we reopen this issue or should I create a new one?
This issue may be related also: https://github.com/lxqt/lxqt/issues/1258

**Comment by tsujan** [comment]
@baptx
https://github.com/lxqt/lxqt/issues/1258 wasn't about LXQt but systemd defaults. Since Feb 2017, I havn't have a single problem with sound.
