### ISSUE TITLE
lxqt-config-globalkeyshortcuts: crash/hang when double-clicking a shortcut

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#771]
This bug exists maybe from the very first version of `lxqt-config-globalkeyshortcuts`. Double-clicking the "Shortcut" column of an entry hangs the configuration dialog "unnaturally" long and actually leads to none of the global key shortcuts work any longer => implies that the process`lxqt-globalkeysd` hangs.

Restarting `lxqt-globalkeysd` - e.g. via `lxqt-config-session` - revives the global shortcuts and brings the system back to normal.

System: Lubuntu 15.04 and LXQt >0.9 (lxqt-globalkeys  0.9.0+bzr153+ amd64)

Screenshot:
![lxqt-globalkeys-hang](https://cloud.githubusercontent.com/assets/440517/9056508/a44ee234-3a93-11e5-96db-98af0fef8866.png)

**Comment by stefonarch** [comment]
Confirmed, same here on arch with git packages some weeks old.

**Comment by paulolieuthier** [comment]
@kuzmas can you take this one, since you implemented the feature? I don't get a segfault, but I do get an issue: when I click a shortcut cell in a row, it turns into a button, but less than one second after that, it gets back to plain text. I can see `Actions::grabShortcutFinished` being called with a reply containing an error.

If you don't have time to do it (and no one else) I think we should remove this feature. Then double-clicking the shotcut cells will open the edit dialog (just like double-clicking other cells).

**Comment by kuzmas** [comment]
@paulolieuthier sorry, I'm not actively working on the project any more.

**Comment by paulolieuthier** [comment]
@kuzmas OK.
