### ISSUE TITLE
Rendering errors?

### ISSUE THREAD

**Issue by jjvattamattom** [lxde/lxqt#781]
![letters](https://cloud.githubusercontent.com/assets/8576642/9198489/16473186-405a-11e5-8ab2-43e0c585a8fe.jpg)

Firefox and Terminator(pictured here) are affected. I have installed LXQT on Kubuntu 15.04. This is an intermittent problem.

I have installed it like:
 ```
sudo add-apt-repository -y ppa:lubuntu-dev/lubuntu-daily
sudo apt-get install lxqt-metapackage lxqt-panel openbox
```
Source: http://linoxide.com/ubuntu-how-to/install-lxqt-desktop-ubuntu/

Here are excerpts of package details:
```
$ dpkg -s lxqt-metapackage
Version: 0.0.1+bzr60+201508012301~ubuntu15.04.1
$ dpkg -s lxqt-panel
Version: 0.9.0.0.0+bzr972+201508032131~ubuntu15.04.1
Depends: libasound2 (>= 1.0.16), libc6 (>= 2.14), libdbusmenu-qt5, libglib2.0-0 (>= 2.12.0), libkf5solid5 (>= 4.97.0), libkf5windowsystem5 (>= 5.6.0+git20150112.0023+15.04), liblxqt0, libmenu-cache3, libpulse0 (>= 0.99.1), libqt5core5a (>= 5.4.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5x11extras5 (>= 5.1.0), libqt5xdg1, libqt5xml5 (>= 5.0.2), libstatgrab9, libstdc++6 (>= 4.1.1), libsysstat-qt5-0, libx11-6, libxcb-xkb1, libxcb1, libxcomposite1 (>= 1:0.3-1), libxdamage1 (>= 1:1.1), libxkbcommon-x11-0 (>= 0.4.0), libxkbcommon0 (>= 0.2.0), libxrender1, lxqt-globalkeys
$ dpkg -s lxqt-common
Version: 0.9.1.0.0+bzr116+201507210101~ubuntu15.04.1
```

**Comment by pmattern** [comment]
I've never seen those findings running LXQt release 0.9 or VCS at various stages on Arch Linux or Siduction but frequently running Ubuntu in a KVM/QEMU virtual machine. The latter wasn't limited to LXQt and could e. g. be seen with Unity as well, though.

Suggestions to further track the problem:
You could try and figure out whether it can be seen with other desktop environments on an otherwise identical system, too.
I you are seeing this in a VM, too, you could try and set up the same system "bare metal".
Set up another Linux distribution under otherwise same conditions.

Definitely looks like a downstream issue to me.

**Comment by jjvattamattom** [comment]
It was bare metal, my office desktop. Thanks for the reminder, I have seen it in KDE. I blamed ALL rendering errors on a bug with `.cache`. Since fixing the cache, I have seen this error only on LXQT.

**Comment by paulolieuthier** [comment]
Does it happen in Terminator only? Try to clean `$HOME/.fontconfig` and `$HOME/.config/terminator` as well.

**Comment by jleclanche** [comment]
This can't be an LXQt issue, closing.
