### ISSUE TITLE
Option to reduce the space between displayed files/folders

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#786]
How do do that, horizontally and vertically, please ? Must I modify all themes, and where ?

**Comment by paulolieuthier** [comment]
There is no option for that yet.

**Comment by pmattern** [comment]
In order to track this further it would be helpful to state and/or get aware whether this is referring to the actual file manager functionality or to PCManFM-Qt handling the desktop.

**Comment by tsujan** [comment]
Implementing grid margin options isn't hard now but first, we have to answer 3 questions:

(1) Should we add separate options for icon+thumbnail view and desktop? (I think, yes).

(2) Also separate options for horizontal and vertical spacings? (I have no idea.)

(3) How many pixels are allowed to be subtracted from vertical margins of desktop cells in order to remove the bottom gap? (IMO, 2 px at most, which means 4 px for spacings).

The default spacing is 6 px (3 px for cell margins) for both desktop and icon view.

**Comment by paulolieuthier** [comment]
IMO,

(1) and (2): No, we should try to keep most settings uniform and simple, not adding options for settings with sane defautls.

(3): I think we should strive for simetry (both vertically and horizontally) for the margins of all sides.

**Comment by tsujan** [comment]
The need for separate horizontal and vertical settings is justified by the fact that most screens are wide.

A separate desktop setting seems necessary to me because, on the one hand, desktop already has its own preferences dialog and, on the other hand, unlike scrollable folder views, it has a limited space.

This screenshot shows what I have in mind:

![margins](https://cloud.githubusercontent.com/assets/981076/12516377/660655f8-c142-11e5-896f-1a6d35bf9af2.png)

IMO, it's clear enough to all users.

Feel free to contradic my argument ;)

**Comment by tsujan** [comment]
I start to work on it little by little. If anyone disagrees on the config appearance and has better suggestions, it could be changed easily.

**Comment by tsujan** [comment]
Done!

![margins](https://cloud.githubusercontent.com/assets/981076/12715368/39335620-c8ef-11e5-9417-1c02a06e1692.png)

**Comment by tsujan** [comment]
Fixed by https://github.com/lxde/pcmanfm-qt/pull/303.
