### ISSUE TITLE
Displacement arrow area is much too small

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#792]
Hi,

the area on the edge of a program window in which a displacement arrow is displayed is much too small.

Regards,
Ettore

**Comment by pmattern** [comment]
Could you please elaborate what you've got in mind here?
I've got a vague idea but the issue is pretty hard to understand. A screenshot wouldn't hurt either.

**Comment by Atalanttore** [comment]
Here it is …

![desktop](https://cloud.githubusercontent.com/assets/628474/9447493/f3e81c98-4a97-11e5-80e2-ba304959a916.png)

**Comment by pmattern** [comment]
That screenshot belongs to #791, doesn't it?

**Comment by paulolieuthier** [comment]
AFAIK, "the area on the edge of a program window in which a displacement arrow is displayed" is responsability of the window manager.

**Comment by Atalanttore** [comment]
My mistake, wrong thread …

**Comment by Atalanttore** [comment]
Second attempt

Displacement arrow appears:
![displacement_arrow_appears](https://cloud.githubusercontent.com/assets/628474/9449347/4ad64b92-4aa2-11e5-9440-17334ecb7485.png)

Too far left:
![too_far_left](https://cloud.githubusercontent.com/assets/628474/9449350/4efe6074-4aa2-11e5-9ebf-ef10b39e0e5e.png)

Too far right:
![too_far_right](https://cloud.githubusercontent.com/assets/628474/9449352/52c37b40-4aa2-11e5-83e0-5cd3466e1a54.png)

**Comment by pmattern** [comment]
The arrows to resize you're referring are corresponding to the window borders which are indeed the window manager's job.
LXQt doesn't and probably never will provide it's own window manager so this issue is a downstream one.

At least on Openbox the window border is handled by themes. The corresponding setting is `border.width`, see [openbox.org/wiki/Help:Themes](http://openbox.org/wiki/Help:Themes#border.width) which is set in files `/usr/share/themes/<theme>/openbox-3/themerc` which can be copied to `~/.local/share/themes/<theme>/openbox-3/` on a per-user basis (apply by running `openbox --reconfigure`).

Aside from this you may want to consider using keyboard + pointer device which is much easier to handle, IMHO.
Again on Openbox drag & drop by left mouse button while holding `Alt` allows for moving, by right mouse button for resizing.
