### ISSUE TITLE
Some icon are missing in the "Choose an Application" dialog box

### ISSUE THREAD

**Issue by hykwok** [lxde/lxqt#814]
When I tried to choose an application for file, I found the dialog box could not show the icon for some applications while the main menu could.
Any log file or tool can help me for troubleshooting?
 
![lxqt_error_001](https://cloud.githubusercontent.com/assets/11486595/9724618/43d3e388-560d-11e5-8e7e-e14a69fae312.png)

**Comment by pmattern** [comment]
Running latest VCS checkouts on Arch Linux I couldn't confirm your findings regarding those Qt development tools but very well regarding JuffEd.

The problem doesn't affect dialog window `Choose an Application` only but the submenu `Open with...` of FHS objects' context menu

![pcmanfm-qt_generic-icons](https://cloud.githubusercontent.com/assets/9860801/9740363/a1b6a142-5654-11e5-9f33-e4ea345de57a.png)

as well and seems to be due to the fact that the icon in need is provided in `/usr/share/pixmaps` *only*.
It would be good if you could try and verify the latter on your system (btw. it would also be good if you stated the OS you're running as well as the way LXQt was installed and the version in use).

Hints how to verify:
Which desktop entry file belongs to JuffEd?
```
$ grep -il juffed /usr/share/applications/*.desktop 
/usr/share/applications/juffed.desktop
```
Alright, it's `juffed.desktop`. So which icon is in use?
```
$ grep Icon /usr/share/applications/juffed.desktop 
Icon=juffed
```
It's an icon named `juffed.<extension>`, maybe juffed.git or juffed.png or juffed.svg. Let's look for a file like this in the usual folders
```
$ find /usr/share/icons/ -iname 'juffed*' 
$
```
→ Nada. How about `/usr/share/pixmaps`?
```
$ find /usr/share/pixmaps/ -iname 'juffed*' 
/usr/share/pixmaps/juffed.png
```
Here were are. So what file is this exactly?
```
$ file /usr/share/pixmaps/juffed.png 
/usr/share/pixmaps/juffed.png: PNG image data, 48 x 48, 8-bit/color RGBA, non-interlaced
```
Okay. If this file gets copied into a suitable subfolder of `/usr/share/icons` (root)
```
# cp -p /usr/share/pixmaps/juffed.png /usr/share/icons/hicolor/48x48/apps/
```
the genuine icon will be used at both locations mentioned above starting with the next session (log out and in again).

**Comment by hykwok** [comment]
After I copied the missing icons to /usr/share/icons/hicolor/, the problem is solved.
Thank you for your information.
