### ISSUE TITLE
Tak Manager maximum button width is in fact the minimum

### ISSUE THREAD

**Issue by intialonso** [lxde/lxqt#816]
What we have now is a fixed size, the default is 400px, this is labeled as the "maximum" so in my understanding, the button should adapt itself to any size below 400px and stop at 400px as this is the "maximum" limit. But it is working as a limit also for the "minimum".

![g3370](https://cloud.githubusercontent.com/assets/7544231/9738465/45b5d734-5611-11e5-8dd1-bc075026d5b4.png)

**Comment by npmiller** [comment]
It's just that the button's width does not adapt to its contents but rather to the available space it has.

When there's enough space the buttons will reach the "maximum" value, however if there's not enough space to display all the buttons at maximum width they will shrink, so in this sense it is not a minimum width, because the buttons can, and will be smaller than this under the right conditions.

This is similar to what was discussed in: lxde/lxqt-panel#171

**Comment by paulolieuthier** [comment]
@npmiller is correct. The buttons may shrink as needed. The width setting is for the maximum width.
