### ISSUE TITLE
menu -> doesn't start program with quotation marks

### ISSUE THREAD

**Issue by mir3x** [lxde/lxqt#843]
Im not sure if it's caused by quotation marks:
I have steam in menu, which is:

LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32/opengl/nvidia/lib:/usr/lib64/opengl/nvidia/lib" steam

and it doesnt start at all ( it works ok under kde )

**Comment by pmattern** [comment]
Setting environment variables in key `Exec` isn't mentioned in the underlying [specification](http://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) so it's hard to tell whether this is supported in the first places. But a line like `Exec=LANG=C firefox %u` doesn't work in both LXQt or Xfce and searching the web yields mainly workarounds like stating bash or env in the said key. All this is  suggesting that environment variables in `Exec` are officially unsupported and that the fact the line you state is working in KDE is rather due to a workaround by this desktop environment.
Also, the fact that you don't just want to assign a value to an environment variable but include an existing one probably doesn't make it any easier.
Nevertheless a line `Exec=env LANG=C firefox %u` is working here so you may want to check whether you can get steam running in a similar way (haven't got an application at hand with similar needs in terms of environment variables).

Somewhat related to #737, btw.

**Comment by mir3x** [comment]
Yes, it works after adding "env".

I just tested under xfce (without env) and it failed with error 
"LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib32/opengl/nvidia/lib:/usr/lib64/opengl/nvidia/lib" ( no such file or directory) 
No idea why quotes and steam are lost.
Thx for reply, i guess u can close that issue.
