### ISSUE TITLE
lxqt-panel: manpage point to a manpage that not exist

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#864]
@pmattern \fBstart-lxqt.1\fR LXQt display management independient starup.

**Comment by jleclanche** [comment]
We'll have a full manpage drive after 0.10

**Comment by pmattern** [comment]
Find a proposal in lxde/lxqt-common#40.

Now that this issue tricked me into having a closer look at man pages of LXQt there seems to be quite a lot of issues to be addressed:
* Attempts should be made to get rid of editing troff source text itself because this is ... cumbersome. Rather stuff like DocBook or reStructuredText should be used.
* Quality is rather poor. Content doesn't make too much sense sometimes as e. g. stated [here](https://github.com/lxde/lxqt-panel/pull/271#issuecomment-153511755), lots of pages are simply missing.   
If we should want to address this in depth, I wonder whether attempts should be made to avoid getting the work done by several contributors in parallel which seems more likely here than with regards to regular source code.
* man pages need to get considered during build.

@jleclanche 
> man pages [...] but we planned to move them to rst

Is there already any ongoing activity regarding the topics stated above? Otherwise we should address that whole thing in one or several issues on the tracker, shouldn't we? Nothing too urgent, though.

**Comment by paulolieuthier** [comment]
@pmattern I don't there is anything ongoing. Feel free to create the issue you mentioned, and I suggest to add a list of checkboxes, one for each component.

**Comment by jleclanche** [comment]
There's nothing ongoing with rst. Ill work on it at some point if nobody else picks it up. For inspiration, take a look at sddm: https://github.com/sddm/sddm/
