### ISSUE TITLE
all panels disappeared

### ISSUE THREAD

**Issue by rogerfranz** [lxde/lxqt#865]
Update 2015 Nov 1. All panels, taskbars, etc, have disappeared completely. I can get a menu of sorts by right-clicking the desktop.

I'm assuming this would be a problem with lxqt-panel, but it could be something else? I'm not even sure where to look at the moment. It did, however, break with this upgrade (listed below).

Suggestions and ideas would be appreciated. Thanks.

Redbeard

Upgrade was (via synaptic on Ubuntu 15.04):
```
 lxqt-powermanagement:amd64 (0.9.0+bzr163+201509302001~ubuntu15.04.1
 0.9.0.0.1~really0.9.0+20150914+201510311753~ubuntu15.04.1)
 libfm-extra4:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 liblxqt-data:amd64 (0.9.0.0.3~really0.9.0+20150911+201510282146~ubuntu15.04.1, 0.9.0.0.3~really0.9.0+20150911+201510310001~ubuntu15.04.1)
 lxqt-admin:amd64 (0.9.0+bzr51+201508301646~ubuntu15.04.1, 0.9.0.0.1~really0.9.0+20150807+201510311608~ubuntu15.04.1)
 libfm-gtk-data:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 lxqt-common:amd64 (0.9.1.0.0+bzr125+201510081946~ubuntu15.04.1, 0.9.1.0.1~really0.9.1+20150922+201510311748~ubuntu15.04.1)
 lxqt-about:amd64 (0.9.0+bzr45+201509021416~ubuntu15.04.1, 0.9.0.0.1~really0.9.0+20150902+201510311608~ubuntu15.04.1)
 lxqt-globalkeys:amd64 (0.9.0+bzr162+201510201601~ubuntu15.04.1, 0.9.0.0.1~really0.9.0+20150914+201510311553~ubuntu15.04.1)
 libqt5xdg1:amd64 (1.2.0.0.1~really1.2.0+20150807+201510280046~ubuntu15.04.1, 1.2.0.0.1~really1.2.0+20150807+201510310046~ubuntu15.04.1)
 lxterminal:amd64 (0.2.0+bzr679+201510181101~ubuntu15.04.1, 0.2.0+bzr682+201510311716~ubuntu15.04.1)
 libsysstat-qt5-0:amd64 (0.3.0.0.1~really0.3.0+20150806+201510241608~ubuntu15.04.1, 0.3.0.0.1~really0.3.0+20150806+201510310301~ubuntu15.04.1)
 dropbox:amd64 (2015.02.12, 2015.10.28)
 libfm-gtk4:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 liblxqt0:amd64 (0.9.0.0.3~really0.9.0+20150911+201510282146~ubuntu15.04.1, 0.9.0.0.3~really0.9.0+20150911+201510310001~ubuntu15.04.1)
 libfm-modules:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 lxqt-session:amd64 (0.9.0.0.1+bzr272+201510201116~ubuntu15.04.1, 0.9.0.0.1+bzr281+201510311830~ubuntu15.04.1)
 ubuntu-release-upgrader-gtk:amd64 (15.04.14.2, 15.04.14.3)
 libpolkit-agent-1-0:amd64 (0.105-8ubuntu3, 0.105-8ubuntu4)
 shotwell-common:amd64 (0.20.2-0ubuntu3, 0.20.2-0ubuntu4)
 shotwell:amd64 (0.20.2-0ubuntu3, 0.20.2-0ubuntu4)
 policykit-1:amd64 (0.105-8ubuntu3, 0.105-8ubuntu4)
 libfm-data:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 lxqt-notificationd:amd64 (0.9.0.0.0+bzr128+201509031346~ubuntu15.04.1, 0.9.0.0.1~really0.9.0+20150903+201510311747~ubuntu15.04.1)
 libfm-tools:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 libpolkit-backend-1-0:amd64 (0.105-8ubuntu3, 0.105-8ubuntu4)
 unzip:amd64 (6.0-13ubuntu3, 6.0-13ubuntu3.1)
 python3-distupgrade:amd64 (15.04.14.2, 15.04.14.3)
 libpolkit-gobject-1-0:amd64 (0.105-8ubuntu3, 0.105-8ubuntu4)
 lxqt-sudo:amd64 (0.9.0+bzr38+201510140816~ubuntu15.04.1, 0.9.0.0.1~really0.9.0+20150908+201510311754~ubuntu15.04.1)
 libfm4:amd64 (1.2.3.0.1+bzr2775+201509121101~ubuntu15.04.1, 1.2.3.0.1+bzr2776+201510302331~ubuntu15.04.1)
 ubuntu-release-upgrader-core:amd64 (15.04.14.2, 15.04.14.3)
```

**Comment by paulolieuthier** [comment]
What is the output lxqt-panel? Run it in a terminal.

**Comment by jleclanche** [comment]
Taking a guess, an upgrade at some point broke lxqt-panel and it couldnt load plugins anymore. That got saved. Now user has an empty panel.

**Comment by paulolieuthier** [comment]
@rogerfranz delete your `~/.config/lxqt/panel.conf` and restart the panel.

**Comment by pmattern** [comment]
Confirming the findings on Lubuntu 15.04 running LXQt from ppa:lubuntu-dev/lubuntu-daily.
Error message launching `lxqt-panel` from the QTerminal
> $ lxqt-panel & 
lxqt-panel: error while loading shared libraries: liblxqt-globalkeys-ui.so.0: cannot open shared object file: No such file or directory

Same thing with `lxqt-runner`. PCManFM-Qt and QTerminal are working flawlessly. Removing all LXQt configuration in ~ doesn't help.
Problem can neither be seen running latest VCS checkouts of LXQt on Arch Linux, Openbox sessions on the very same Lubuntu system are working flawlessly, too. So this is definitely a downstream issue affecting that *buntu PPA.

@gilir 
Could you please have a look at this one?

@rogerfranz 
Could you please state the OS you're using and the way you installed LXQt? These information should possibly provided whenever it's reasonable in order to ease tracking problems.
Possible workarounds: (i) Have a look at the desktop's context menu. If it's featuring an item "Terminal Emulator" then you're most likely running Openbox and have LXQt configured to show that display manager's context menu. The said item is set to launch QTerminal on Lubuntu which in turn allows for launching all applications that do run. Otherwise there will be a topic "Desktop Preferences" in the context menu. The corresponding GUI allows for replacing LXQt's context menu with the window manager's one. (ii) Use LXpanel from package `lxpanel`.
If @gilir shouldn't respond in time you could open a bug on https://bugs.launchpad.net/lubuntu-next.

**Comment by rogerfranz** [comment]
OS is Ubuntu 15.04. Installation is via Synaptic, using repository http://ppa.launchpad.net/lubuntu-dev/lubuntu-daily/ubuntu

lxqt-panel yields:

>~$ lxqt-panel
>lxqt-panel: error while loading shared libraries: liblxqt-globalkeys-ui.so.0: cannot open shared object file: No such file or directory

The missing library is available in synaptic.  I installed it to see what would happen.
Panels are restored after installing the missing library and starting lxqt-panel. Looks like a dependency issue in the package.

Thanks all. I will report the bug.

**Comment by gilir** [comment]
Sorry it's a side effect of the ongoing work on the PPA. You need to install liblxqt-globalkeys* packages. A proper fix should appear next time lxqt-panel is correctly rebuilt.
