### ISSUE TITLE
panel plugins: GUIs not considered with regards to auto-hide

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#871]
lxqt-panel has the option to auto-hide the panel. The auto hide works.

However, when tasks are grouped together and the mouse is hovering above one of the grouped tasks, the panel disappears after one second, making it very hard to click on it.

![2015-11-03-115924_1680x1046_scrot](https://cloud.githubusercontent.com/assets/6639859/10906524/768bbe36-8222-11e5-8914-f2d3ad5805eb.png)

The suggestion is to temporary disable autohide, when the mouse is hovering one of the grouped tasks.

**Comment by pmattern** [comment]
Confirmed as stated above. Arch Linux i686 or x86_64 with LXQt from latest VCS checkouts.

Auto hiding should indeed get disabled when the pointer is hovering over those grouped tasks.

**Comment by ArthurBorsboom** [comment]
More or less the same happens to the start menu.
When the panel hides, it feels like the start menu is floating.

![start-menu](https://cloud.githubusercontent.com/assets/6639859/10933454/e5efa9c0-82d8-11e5-85f4-a03a80df6da9.png)

**Comment by pmattern** [comment]
The problem seems to affect basically every panel plugin featuring an appropriate GUI. Hovering over a GUI belonging to a panel plugin isn't considered as an activity to prevent the panel from auto-hiding which hence takes places.
Changed the title accordingly.

E. g. plugin-volume is e. g. affected as well
![lxqt-panel_auto-hide-vs-plugin-guis](https://cloud.githubusercontent.com/assets/9860801/10942778/c8269708-8311-11e5-8d08-b7cf6183cc29.png)

**Comment by ArthurBorsboom** [comment]
:+1:

**Comment by pmattern** [comment]
In the meantime I had a look at some other desktop environments, wondering whether the behaviour eventually has to be considered a feature:

The findings depicted in this issue can *not* be seen in KDE Plasma 5, Cinnamon, Mate and Xfce. In all of these hovering over objects like main menu or ruler of volume control prevents the panel from auto hiding. Only exception I could see was a calendar of Mate's clock applet, pretty similar to plugin-[world-]clock.
LXDE behaves as discussed in this issue, GNOME 3 [Classic] seems to need extensions to hide the panel in the first place, didn't look into this further.

Considering these findings and this issue's screenshots I'd personally tend to call the behaviour a bug, not a feature.

**Comment by palinek** [comment]
@pmattern thanks for reviewing other environments.

**Comment by jleclanche** [comment]
This is a bug regardless of what other environments do :p

**Comment by palinek** [comment]
Could you, guys, test if the lxde/lxqt-panel#275 fixes the behaviour.

**Comment by ArthurBorsboom** [comment]
On Arch Linux I have uninstalled the community version of the package lxqt-panel and installed the AUR version lxqt-panel-git. This package uses git+https://github.com/lxde/lxqt-panel.git

The package has been compiled and installed. After running I did not see a difference w.r.t. the autohide issue.

**Comment by pmattern** [comment]
@ArthurBorsboom 
Mixing LXQt components from different development stages like you did with lxqt-panel from VCS vs. all the rest from release 0.10 is promoting all kinds of wiredness. Personally I started considering findings from systems like this just useless at some point.
In this particular case you may also see the discussion in lxde/lxqt-panel#275.

**Comment by palinek** [comment]
> On Arch Linux I have uninstalled the community version of the package lxqt-panel and installed the AUR version lxqt-panel-git. This package uses git+https://github.com/lxde/lxqt-panel.git

The change is not in master yet.

**Comment by ArthurBorsboom** [comment]
In that case, I will test the package once it gets updated in Arch.
Nevertheless, thanks for your effort.

**Comment by palinek** [comment]
It' now in master...

**Comment by ArthurBorsboom** [comment]
I have tested the same way as before and I can confirm that the issue has been resolved.
Great work.

**Comment by pmattern** [comment]
@ArthurBorsboom 
You may want to consider switching to the AUR VCS packages altogether.
All in all they admittedly still make for the better UX right now.
Also, using these is much more helpful with regards to eventual issues. Serious malfunction is taking place rarely, drawbacks due to this can be avoided by updating when the system isn't just urgently needed and keeping the old packages as backup. Assuming some basic knowledge of AUR helpers installing all LXQt components can be scripted rather easily.
