### ISSUE TITLE
lxqt-runner: enable standalone use

### ISSUE THREAD

**Issue by warptozero** [lxde/lxqt#920]
I would like to user lxqt-runner standalone in another de/wm (awesome in my case). As it now stands lxqt-globalkeysd has to be run alongside it to have it respond to keypresses.

Would it be possible to introduce a command-line flag that directly calls the runner (or something to that effect)?

**Comment by palinek** [comment]
@warptozero there you go, have a look in lxde/lxqt-runner#37

**Comment by palinek** [comment]
... so we have now 2 possibilities implemented:
- lxde/lxqt-runner#37 -> one shot show window, daemon not running all the time
- lxde/lxqt-runner#38 (needs also lxde/liblxqt#76) -> first invocation runs the daemon, every next `lxqt-runner` invocation just shows/activates the daemon's window

**Comment by palinek** [comment]
@jleclanche, @luis-pereira, @PCMan, @paulolieuthier, @pmattern Could you, guys, tell your opinion on this?

**Comment by paulolieuthier** [comment]
Second option is much better IMO.

**Comment by warptozero** [comment]
I've compiled and tested both a bit. The first option works, but is rather sluggish. The second option seemed to work looking at the way the invocations behaved but no window pops up. No error messages though.

**Comment by pmattern** [comment]
Not following here:
The whole point of this issue is using `lxqt-runner` without lxqt-globalkeys, right? But if `lxqt-globalkeysd` gets stopped both lxde/lxqt-runner@b3a9b2f and lxde/liblxqt@d5cd5a2 / lxde/lxqt-runner@7298031 stop working here, too.
Am I missing something?

That I side I'm basically -1 on this issue anyway.
lxqt-runner is a really integral part of the desktop environment as both `lxqt-runner` itself and `lxqt-globalkeysd` on which it depends for now are LXQt modules. So unlike regarding stand-alone applications like LXImage-Qt or PCManFM-Qt (desktop manager itself, not invocation as LXQt Module to handle the desktop) I don't see the point in tweaking lxqt-runner just to get it running outside LXQt.
If at all this should only be done if there's really no downside for LXQt itself, IMO.

**Comment by paulolieuthier** [comment]
@warptozero did you also merged liblxqt's PR, as @palinek explained? It's a requirement for the second option.

@pmattern I think LXQt components should be as generic and independent as possible. In an ideal world, there would be a shortcut daemon DBUS specification, so that lxqt-globalkeysd would be only one more implementation of it. That way, users could replace it with any other.

**Comment by warptozero** [comment]
@paulolieuthier Oops, I completely overlooked the liblxqt commit. The second option works flawless now. And if there are no objections concerning the specific implementation it seems like a great solution to me.

On a side note: as an end user I really appreciate the modularity of the lxde/lxqt desktop(s). The fact that most components are replaceable or separately usable is one of the main attractions to me. So I would applaud any movement to strengthen that philosophy.

@palinek (and others) Thanks for the swift response.

I'll continue use the second implementation and report any bugs that might arrive.

**Comment by palinek** [comment]
> That aside I'm basically -1 on this feature anyway.
lxqt-runner is a really integral part of the desktop environment as both lxqt-runner itself and lxqt-globalkeysd on which it depends for now are LXQt modules. So unlike regarding stand-alone applications like LXImage-Qt or PCManFM-Qt (desktop manager itself, not invocation as LXQt Module to handle the desktop) I don't see the point in tweaking lxqt-runner just to get it running outside LXQt.

As you can see here, people can/want use lxqt-runner standalone. If lxqt-globalkeysd isn't running, the lxqt-runner will not receive the shortcut via lxqt-globalkeysd DBus API... so basically the runner's window can't be shown at all. This "drawback" is overriden in the 2nd implementation... as the user can show the window by executing the lxqt-runner binary -> so one can configure e.g. openbox to achieve this by shortcut.

IMO the implementation has no (or very little) performance hit (just the deamon listens to one DBbus signal more) over the state before.

**Comment by pmattern** [comment]
@palinek 
Thanks for explaining. I didn't realize the shortcut to invoke lxqt-runner's GUI has to be defined at the window manager level. Now the second implementation (lxde/liblxqt@d5cd5a2 / lxde/lxqt-runner@7298031) is working is working here, too.
As long as binary lxqt-runner isn't running yet hitting the shortcut in question will just launch the binary, lxqt-runner's GUI comes up only upon hitting the shortcut the second time onwards.

**Comment by paulolieuthier** [comment]
@palinek go ahead and ship it. Nice work :+1:.
