### ISSUE TITLE
[lxqt-config] Regression bugs in lxqt-config-monitor

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#923]
1. Loading saved configurations does not work here.
2. The UI is less intuitive than previous versions and I'm not able to put my two monitors side by side with the new UI.
3. The handy quick options available in older versions are gone.

BTW, Some code cleanup is needed.
1. Instead of storing a json byte stream in a key of QSettings, use QSettings properly, or just save a json file.
2. Autostart can be created using libqtxdg, which is more reliable.

If nobody is working on this, I'll try to create some fixes later.

**Comment by selairi** [comment]
Sorry, I'm working and I haven't got enough time. Maybe next week I
will write some code.

> 1 Loading saved configurations does not work here

There was a bug on 0.10 release. But I was fixed in git master branch.

>  I'm not able to put my two monitors side by side with the new UI

When you connect two or more monitors, the graphical UI allows you to
drag monitor and to change positions. What is wrong?

> use QSettings properly, or just save a json file

I'm working on save settings dialog. I use json byte stream in a key
of QSettings because I will need and array of settings. You can save
several settings from different hardware. If you have a laptop, you
will connect it to your screen, projectors and you will need save
those settings in order to make your work easier. But I don't finish
the save settings dialog yet. Please, don't remove it.

> 2 Autostart can be created using libqtxdg, which is more reliable

OK.

Sorry, but I can not write code now.


2015-12-21 7:09 GMT+01:00, PCMan <notifications@github.com>:

**Comment by PCMan** [comment]
@selairi You don't really need to say sorry about anything.
Your time and efforts are appreciated and I owe you a big "Thank you".
I just documented the problems I saw so later we'll remember to work on them.
Please take your time. :-)
I'm testing the latest code from git, not 0.10, but loading the saved configurations does not work here. I don't have enough time to do further debugging, though.
The new UI is powerful, but it's a little bit confusing.

1. If you layout the monitors using DND, that's fine. However, after you finish it, the settings pages of these monitors do not update properly. In this case, the type of display should be automatically changed to "positioned manually."
2. If you set monitor1 to "Right of" monitor2, and then set monitor 2 to be positioned at "Right of" monitor 1, what will happen? Apparently, this is contradiction but the UI allows this configuration. It just fails silently after you apply the settings.
3. Putting the "primary monitor" setting in the combo box creates a new UX problem. How can you set "primary monitor" if both monitors are set to be "positioned manually"? You'll have no way to select the primary monitor.
4. If you plug in two monitors of the same type, there is no way to distinguish them in the UI. So you can layout the monitors in the wrong order easily.
Thanks!

**Comment by PCMan** [comment]
@selairi If you need to store different sets of settings inside a QSettings object, instead of making them json byte streams, a possibly simpler way is like this. Just put them in different groups and store the list of group names to easily enumerate them.

[Global Settings]
names=Config1;Config2;Config3;

[Config1]
Resolution=....
Position=...

[Config2]
Resolution=....
Position=...

**Comment by selairi** [comment]
Thanks for your report. I will fix these problems.

2015-12-22 15:21 GMT+01:00, PCMan <notifications@github.com>:

**Comment by selairi** [comment]
> 1 Loading saved configurations does not work here

I have found a X11 bug. If I run xrandr command at start, it will show:

 Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
 DP1 disconnected (normal left inverted right x axis y axis)
 HDMI1 connected 1366x768+0+0 (normal left inverted right x axis y
axis) 410mm x 230mm
    1366x768      59.79*+
 VGA1 disconnected (normal left inverted right x axis y axis)
 VIRTUAL1 disconnected (normal left inverted right x axis y axis)

But if I wait a few seconds, xrandr will show:

 Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
 DP1 disconnected (normal left inverted right x axis y axis)
 HDMI1 connected primary 1366x768+0+0 (normal left inverted right x
axis y axis) 410mm x 230mm
    1366x768      59.79*+
    1280x720      60.00
    1152x720      59.97
    1024x768      60.00
    1024x576      59.97
    800x600       60.32
    640x480       60.00
 VGA1 disconnected (normal left inverted right x axis y axis)
 VIRTUAL1 disconnected (normal left inverted right x axis y axis)

I have also found screen modes changes their id, then kscreen method
"output->setCurrentModeId()" doesn't work. I fixed it, and
lxqt-config-monitor waits until modes are ready, about 10 seconds in
my computer! This is ugly, because LXQt session starts and ten seconds
later video modes are applied.

Could you be so kind to test it?

Thanks

**Comment by selairi** [comment]
I have fixed all those points:

> 1 Loading saved configurations does not work here
> 2 The UI is less intuitive than previous versions and I'm not able to
> put my two monitors side by side with the new UI
> 3 The handy quick options available in older versions are gone
>
> BTW, Some code cleanup is needed
> 1 Instead of storing a json byte stream in a key of QSettings, use
> QSettings properly, or just save a json file
> 2 Autostart can be created using libqtxdg, which is more reliable

I also added a simple tool in order to change the brightness (libKScreen 
can not change the brightness yet).

More suggestions?
