### ISSUE TITLE
Claws-Mail SysTray-icon broken 

### ISSUE THREAD

**Issue by renegat** [lxde/lxqt#945]
lxqt-panel 0.10.0-5
claws-mail 3.13.2-1
4.3.3-2-ARCH x86_64 GNU/Linux

With configuration -> preferences -> plugins -> notification -> systrayicon -> enabled in claws-mail
after starting claws-mail the systray icon appears too big and without function in the notification area of the lxqt-panel.

When doing right-click on the panel, panel -> configure panel the icon becomes normal size and the functions are back (left click to focus/maximize claws-mail window, right click for mail specific commands).

I can remember similar issue with claws-mail / Sylpheed and lxde lxpanel some years ago so I think this is a regression.

![20160126-175731](https://cloud.githubusercontent.com/assets/5675028/12588221/e8320d8e-c457-11e5-9e8f-a96771a2f5cd.jpg)

![20160126-180345](https://cloud.githubusercontent.com/assets/5675028/12588143/9126dd30-c457-11e5-9a00-1ef5a7913e92.jpg)

**Comment by palinek** [comment]
@renegat can you, please, check if the lxde/lxqt-panel#300 fixes the issue on your side?

**Comment by palinek** [comment]
@renegat should you encounter the problem after the lxde/lxqt-panel@9dc1ba0, please reopen this issue

**Comment by renegat** [comment]
Sorry but I'am just a user trying to help make lxqt better.
I cannot do anything with instructions like 'check if the lxde/lxqt-panel#300 fixes the issue'. I was not able to find anything to install, to download or to compile, the git version available in arch linux aur is older (0.9.0.155.gbc4d32b-1) than the one in the official (0.10.0-5) repositories.
The issue still persits.
If you want me to give more informations please give more detailed instructions how to do so or where to find guidance to give more helpful information.
Thank you very much;
renegat

**Comment by pmattern** [comment]
> Sorry but I'am just a user trying to help make lxqt better.

... which is perfectly okay in the first place. So you're an Arch Linux user already. In order to help out you'd hence have to dig into that ABS / AUR thing a bit deeper.
Some hints:

Basic  information can be found in the Arch wiki at [Arch Build System](https://wiki.archlinux.org/index.php/Arch_Build_System) and [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository).

Testing distinct commits or branches of source code is rather easy as [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) allows for stating them explicitly in variable `source`, see [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#VCS_sources).
So all you need to do is `git clone` the AUR sources according to the link stated at "Git Clone URL" on every AUR package's site, modify variable source to something like `source=("git+https://github.com/lxde/$_pkgname.git#commit=1234567")` or `source=("git+https://github.com/lxde/$_pkgname.git#branch=foobar")`, run `makepkg -s` in that directory and install manually by running `pacman -U <path to *.pkg.tar.xz>`.
A commit chosen that way gets picked automatically from any arbitrary branch so doesn' have to be in branch `master`.

Regarding this issue it's even easier as palinek merged already into master. So you just have to install AUR package `lxqt-panel-git`. Don't get fooled by the apparently outdated version of that package. Versions of VCS packages get updated during build.

Running up to date code of a single component and rather older versions of all the rest is rather error prone. So you may consider switching to the VCS packages from the AUR as a whole. IMO these make for the better UX anyway so far.
You could look into the [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers) and use a script like [this](https://gist.github.com/pmattern/8056c4bd7104ae640b79).
Proceeding can be fine-tuned e. g. by modifying SRCDEST of makepkg.conf, see e. g. [makepkg](https://wiki.archlinux.org/index.php/Makepkg) to avoid downloading the sources as a whole each time.

**Comment by jubalh** [comment]
It works perfectly with:
lxqt-panel 0.10.0
claws 3.13.2
on openSUSE Tumbleweed for me.

**Comment by renegat** [comment]
With lxqt-panel-git 0.10.0.55.gb0f6d23-1 and Claws Mail 3.13.2 the issue is gone here
