### ISSUE TITLE
Zombie apps taking up space in lxqt-panel

### ISSUE THREAD

**Issue by Jemi** [lxde/lxqt#948]
As I write this, I have 'zombie' entries on my panel for vlc and for wine. They all correspond to programs I had open but subsequently closed. 'wine - 6 windows' shows up on one tab (and hovering over it brings up 6 zombie tabs) and just 'vlc' on the other. I don't know how this happened, so I hope this is not too difficult to reproduce. Please let me know if there's a way I can help make this reproducible. 

LXQT version: 0.10
Operating System: Linux
Distro: Gentoo
Architecture: amd64

**Comment by pmattern** [comment]
Seems a bit related go #946.

**Comment by goetzc** [comment]
I have seen this bug some time ago, not sure if in the current version (0.10) or in older versions.

**Comment by cyberbeat** [comment]
I have the same problem with wine apps (they stay in taskbar after been closed)
LXQT: 0.10, Openbox, Opensuse, x86-64

**Comment by palinek** [comment]
Could anyone observing this issue check if the issue persists also with the latest git?

**Comment by tsujan** [comment]
@palinek I saw this behavior about 4 months ago. I was going to open an issue but after an LXQT upgrade (directly compiled from the latest sources), it totally disappeared. I've never seen it since then, neither in Wine, nor in VirtualBox, or .... So, I think it's really fixed.

Considering the fact that none of us has been able to reproduce it, logically, we can just wait a month or so for distros to upgrade all LXQT packages and then see if it'll happen to anyone again. In the meantime, more useful info may be gathered.

**Comment by palinek** [comment]
I believe it is fixed... if not, please, reopen.
