### ISSUE TITLE
lxqt-config-brightness-settings should have minimal brightness set

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#973]
Testing the new feature I accidently turned too much the button and my monitor (VGA) got completely dark and I lost control over brightness setting, even virtual consoles tty were dark, I had to hard reset the system. 

IMHO this behavior should be not possible.

**Comment by selairi** [comment]
Ok. I will add a warning and a timer in those cases.

**Comment by pmattern** [comment]
What I've also been wondering: couldn't we just introduce some shortcuts, maybe as simple as `+` and `-`, to adjust the values?
These would be available even if the display is black and could hence help mitigate this problem, too.

**Comment by pmattern** [comment]
Just saw that `Arrow {Left,Right}` are already adjusting brightness here. Dual-monitor system running Arch Linux, only one monitor gets adjusted by those keys, choice seems unclear but unrelated to setting `--primary` of `xrandr`.

Eventually adding a to the GUI about those or some still to be introduced shortcuts would do the job, too?

Personally, I'm not too much in favour of that warning / timer stuff. I figure situations can very well exist were kind of muting one display is just wanted and a timer or so would just be a hindrance then.

**Comment by stefonarch** [comment]
My problem was that I lost also focus, I tried some shortcuts. I think just never  going below 10% should do.

**Comment by Vladimir-csp** [comment]
Disabling backlight is a feature. Perhaps a better way would be showing a popup displaying brightness shortcuts before brightness go to 0, and actually switch to 0 on second button press.

It also can be tricky governing backlight with keys via X as certain systems with certain kernel kernel parameters process brightness keys on hardware level.

**Comment by selairi** [comment]
I think showing keys shortcuts to change brightness could be more useful. Brightness must not be saved because users could set their brightness to 0 and they would be able to recover their screens rebooting.

Desktop computers don't usually let you change brightness by software. You must use your screen buttons to do it. In that case, lxqt-config-brightness changes colours in order to simulate brightness change (it is the knob). Slider of lxqt-config-brightness is shown when hardware lets change backlight using software (example laptops).

Maybe we must not use same keys shotcuts than laptops, because some systems process brightness keys on hardware level and brightness is increases or decreases twice. Moreover, desktop computers have not got specific keys to change brightness.

**Comment by luis-pereira** [comment]
IMO this issue should be solved for the upcoming release.

**Comment by paulolieuthier** [comment]
AFAIK Plasma also allows one to make the screen completely dark that way. I agree we should improve the user experience here by at least offer an option to set a minimum brightness level. But I don't think this is a release blocker.

**Comment by agaida** [comment]
One forget about nearly white - btw, a reset and save button would be nice.  At least it should be possible to reset to the old settings with a simple abort.

**Comment by agaida** [comment]
upps, sorry

**Comment by luis-pereira** [comment]
@paulolieuthier Plasma put limits to the brightness the user can set. On my system it follows the laptop keys. IMO a completlty white/dark screen should not be allowed. Most users can't get out of it.
![screen-2016-07-01-16-28-19](https://cloud.githubusercontent.com/assets/62877/16526812/01c3a716-3fab-11e6-9236-b09624d86f8a.png)

**Comment by paulolieuthier** [comment]
Any idea on how to do it?

**Comment by luis-pereira** [comment]
Yes. But, probably @selairi can do it much faster. It's is code I think.

**Comment by pmattern** [comment]
I still think setting outputs completely dark should at least stay available as an option. This may make a lot of sense e. g. to have controls of a video player on one monitor and the video itself on an other.
Of course the option could be disabled by default, the arguments in favour of avoiding black screens by default are obviously reasonable.

**Comment by paulolieuthier** [comment]
@luis-pereira could you share your idea?

**Comment by selairi** [comment]
Maybe, the best option is forgiven dark screens, but I can add an advanced
settings dialog and advanced users could enable it.


El sábado, 30 de julio de 2016, Paulo Lieuthier <notifications@github.com>
escribió:
> @luis-pereira could you share your idea?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/y6aFvRSfkwNBmkYNPSLgZlZVYUNTRn1QTR2PXb2Z4cm8INEr18LbyaNE79c64273sv5MaDvFauk6QNjFMw7FQ-G9ulR04BsVfjNnICrzGIXoZXBtT_5eF49Hvx3-iEZe7gGSg6W5pmkAszPXMsPS1YT3a2XNMQ=s0-d-e1-ft#https://github.com/notifications/beacon/ABG_g-EtYIx5fpd74dgqcNsz-m23IIyWks5qa55HgaJpZM4HqsmV.gif>

**Comment by luis-pereira** [comment]
@selairi Glad to hear from you.
My laptop does not support backligtht, i.e. [MonitorInfo::isBacklightSupported()](https://github.com/lxde/lxqt-config/blob/master/lxqt-config-brightness/monitorinfo.cpp#L37) returns `false`. So I end with this interface: 
![screen-2016-08-01-11-13-39](https://cloud.githubusercontent.com/assets/62877/17296720/842d9696-57fa-11e6-8cf5-f75ce9fc89ef.png)
It works by manipulating gamma. It has no limits and after the screen is completely dark, it's almost impossible (for a regular user) to make not dark again.
My idea is/was to use the same sliding interface for both cases (backlightSupport() true or false). KDE is able to do it. Using the same laptop:
![screen-2016-07-30-22-18-27](https://cloud.githubusercontent.com/assets/62877/17297099/2079398c-57fc-11e6-8a2c-156e963f7b73.png)

**Comment by selairi** [comment]
I have found devices that minimum brightness is not dark. The brightness
and gamma controls are required. Some linux distributions install default
xorg driver, no backlight control. If your graphic card is intel, please,
install xorg-intel driver.

I am thinking about using /proc, backlight class and polkit in order to
change backlight. My tests shows that it works in xorg and wayland (weston).

El lunes, 1 de agosto de 2016, Luís Pereira <notifications@github.com>
escribió:
> @selairi Glad to hear from you.
> My laptop does not support backligtht, i.e.
MonitorInfo::isBacklightSupported() returns false. So I end with this
interface:
> <
https://ci4.googleusercontent.com/proxy/ZquPvPSzbkZqgft3nh6BLUFN572qzc3hQ8QVkhbr2t1xZPxsmct0lMfQ027UzzdBM1SjXvbl6oYxwrXNiQGnO42X6KBzHHx_4gsjr98E6fzwIzw0F3WEJBL_vaLcUsYQ3tH8GOJ7iG3Zfpk7rfN23RnpepaGE3td=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/62877/17296720/842d9696-57fa-11e6-8cf5-f75ce9fc89ef.png
>
> It works by manipulating gamma. It has no limits and after the screen is
completely dark, it's almost impossible (for a regular user) to make not
dark again.
> My idea is/was to use the same sliding interface for both cases
(backlightSupport() true or false). KDE is able to do it. Using the same
laptop:
> <
https://ci5.googleusercontent.com/proxy/b--l0EjBcyjxu74Lch9z8eOvmK_qzAdog9DZmuo3X6P9Gw6Pf8Ke6tcyO8RRpfV8EWBvCBxfpmgbj2qJvzpnuU9xomLRYQUf8mBFoijfoychPwhvvuQiU9OYXNGRkMYIhc_sEQ2NhxYT_OKptvLHSzziBV9ry-TJ=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/62877/17297099/2079398c-57fc-11e6-8a2c-156e963f7b73.png
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/JEHJxR3JyY4PfEacxrD97WJu3JEiThwSTnqNwl66oOaC0CQ8UW_gNplwutjBbdWy6Gp3GloIk_iGmAJ34hw_ItlFEvTcjaKsGMLThri4cnvhRkdgmJmCQWDgkse38yAkJU8L_73jf7eKMqcv1TRyOs0n08ofow=s0-d-e1-ft#https://github.com/notifications/beacon/ABG_g7nDhgRTOJ-OXAMC21sE7c1bsH41ks5qbgHtgaJpZM4HqsmV.gif>

**Comment by luis-pereira** [comment]
@selairi My laptop keys brightness don't allow for completely dark screen. KDE brightness settings follow the keys behavior. Tweaking the gamma should be reserved to an Advanced settings page, IMO
My graphic card is an GeForce G 105M. I'm using nvidia-340xx driver on Arch. 

I think that's possible to take KDE `BacklightHelper` class and use it with minor tweaks. Check [here](https://quickgit.kde.org/?p=powerdevil.git&a=blob&h=1382dd09938840371dbf34312fe2e8093abfbe10&hb=d6756697d63e7f034187c691a596fbb9ccefee1e&f=daemon%2Fbackends%2Fupower%2Fbacklighthelper.h) and [here](https://quickgit.kde.org/?p=powerdevil.git&a=blob&h=376f463425f69b7c509053a652a30d1f90a761ac&hb=d6756697d63e7f034187c691a596fbb9ccefee1e&f=daemon%2Fbackends%2Fupower%2Fbacklighthelper.cpp).

**Comment by paulolieuthier** [comment]
> My laptop keys brightness don't allow for completely dark screen. KDE brightness settings follow the keys behavior.

That's the thing. My laptop allows me to make it completely dark. Of course we can set a minimum in the slider, but we would still be able to make the screen completely dark using the keys. What I thought was to listen to backlight changes and once the screen gets completely dark, we restore some light.

**Comment by luis-pereira** [comment]
@paulolieuthier But if you make it completely dark with the keys, every user knows how to get out of it.Just use the other key.
But with our button thing it's more complicated. Sure we can use the arrows keys. But probably most user  won't even read that. They will go direct to the knob and set it with the mouse.

**Comment by paulolieuthier** [comment]
So it's only a UI problem? easy to fix.

**Comment by luis-pereira** [comment]
It's also a Ui problem. But not only. When there is no backlight support we should use the other methods to control it. We can and should use the `/sys/class/backlight/`

**Comment by selairi** [comment]
> When there is no backlight support we should use the other methods to
control it. We can and should use the /sys/class/backlight/

That is the point. Some xorg drivers can not change backlight, but
/sys/class/backlight usually may change it. I have tested it under weston
and it works. Moreover, it is simple, but polkit must be used. Xorg-intel
driver uses that method.



>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/Pk5EVFp5pPvI4x_CRKLK7BMUj58OmiPnLTFKqhLFRf8p8rpdjBDJjeiyzu4yaTl6DkUlFl-ju7jPSS-GiAPzsEZ6c5nRSXUKc4Vkjx2EOedazgh1oQe1pSL-bc4d4Hja7MB9XSSOr-Xvm9PhJn8SVFo6NDDxpQ=s0-d-e1-ft#https://github.com/notifications/beacon/ABG_gxzYaaTiazthtTO5miwnJzbbxIeDks5qbiVYgaJpZM4HqsmV.gif>

**Comment by jeremywh7** [comment]
Could the resolution to this be as simple as a minimum brightness limit checkbox that is defaulted on?  Then if a user wants to set a lower brightness (uncheck the box), there is a popup warning that the screen could become black, and to correct it, use the hotkeys (which it could query to remind the user what they are) or whatever alternative method (arrow keys?).  And perhaps the popup warning could also be invoked if the hotkeys hit the minimum limit, and clicking "Ok" would automatically also disable the limit.

**Comment by selairi** [comment]
It's also a Ui problem. But not only. When there is no backlight support we
> should use the other methods to control it. We can and should use the
> /sys/class/backlight/
>
I have done some test using /sys/class/backlight/ and Polkit. It is a
command line tool, it can be found in:

https://github.com/selairi/lxqt-backlight

It has to use pkexec (Polkit):

    pkexec lxqt-backlight --inc

Increases backlight.

    pkexec lxqt-backlight --dec

Decreases backlight.

/sys/class/backlight/ is really simple. Example of reading and setting
backlight level:

char *driver = get_driver();

if( driver == NULL )

   return;

int max_value = read_max_backlight(driver);

int actual = read_backlight(driver);

int value = 100;

if(value<max_value && value>0) {

   set_backlight(driver, value);

}

free(driver);

**Comment by palinek** [comment]
Plase, see if the lxde/lxqt-config#100 can be considered as a solution.
